graph TD
    N0[__init__.py]
    N1[dashboard_fixtures.py]
    N2[__init__.py]
    N3[__init__.py]
    N4[blanket_order.js]
    N5[blanket_order.py]
    N6[blanket_order_dashboard.py]
    N7[test_blanket_order.py]
    N8[__init__.py]
    N9[blanket_order_item.py]
    N10[__init__.py]
    N11[bom.js]
    N12[bom.py]
    N13[bom_dashboard.py]
    N14[bom_list.js]
    N15[bom_tree.js]
    N16[test_bom.py]
    N17[__init__.py]
    N18[bom_creator.js]
    N19[bom_creator.py]
    N20[bom_creator_list.js]
    N21[test_bom_creator.py]
    N22[__init__.py]
    N23[bom_creator_item.py]
    N24[__init__.py]
    N25[bom_explosion_item.py]
    N26[__init__.py]
    N27[bom_item.py]
    N28[__init__.py]
    N29[bom_operation.py]
    N30[__init__.py]
    N31[bom_scrap_item.py]
    N32[__init__.py]
    N33[bom_update_batch.py]
    N34[__init__.py]
    N35[bom_update_log.js]
    N36[bom_update_log.py]
    N37[bom_update_log_list.js]
    N38[bom_updation_utils.py]
    N39[test_bom_update_log.py]
    N40[__init__.py]
    N41[bom_update_tool.js]
    N42[bom_update_tool.py]
    N43[test_bom_update_tool.py]
    N44[__init__.py]
    N45[bom_website_item.py]
    N46[__init__.py]
    N47[bom_website_operation.py]
    N48[__init__.py]
    N49[downtime_entry.js]
    N50[downtime_entry.py]
    N51[test_downtime_entry.py]
    N52[__init__.py]
    N53[job_card.js]
    N54[job_card.py]
    N55[job_card_calendar.js]
    N56[job_card_dashboard.py]
    N57[job_card_list.js]
    N58[test_job_card.py]
    N59[__init__.py]
    N60[job_card_item.py]
    N61[__init__.py]
    N62[job_card_operation.py]
    N63[__init__.py]
    N64[job_card_scheduled_time.py]
    N65[__init__.py]
    N66[job_card_scrap_item.py]
    N67[__init__.py]
    N68[job_card_time_log.py]
    N69[__init__.py]
    N70[manufacturing_settings.js]
    N71[manufacturing_settings.py]
    N72[test_manufacturing_settings.py]
    N73[__init__.py]
    N74[master_production_schedule.js]
    N75[master_production_schedule.py]
    N76[test_master_production_schedule.py]
    N77[__init__.py]
    N78[master_production_schedule_item.py]
    N79[__init__.py]
    N80[material_request_plan_item.js]
    N81[material_request_plan_item.py]
    N82[test_material_request_plan_item.py]
    N83[__init__.py]
    N84[operation.js]
    N85[operation.py]
    N86[operation_dashboard.py]
    N87[test_operation.py]
    N88[__init__.py]
    N89[plant_floor.js]
    N90[plant_floor.py]
    N91[test_plant_floor.py]
    N92[__init__.py]
    N93[production_plan.js]
    N94[production_plan.py]
    N95[production_plan_dashboard.py]
    N96[production_plan_list.js]
    N97[test_production_plan.py]
    N98[__init__.py]
    N99[production_plan_item.py]
    N100[__init__.py]
    N101[production_plan_item_reference.py]
    N102[__init__.py]
    N103[production_plan_material_request.py]
    N104[__init__.py]
    N105[production_plan_material_request_warehouse.js]
    N106[production_plan_material_request_warehouse.py]
    N107[test_production_plan_material_request_warehouse.py]
    N108[__init__.py]
    N109[production_plan_sales_order.py]
    N110[__init__.py]
    N111[production_plan_sub_assembly_item.py]
    N112[__init__.py]
    N113[routing.js]
    N114[routing.py]
    N115[routing_dashboard.py]
    N116[test_routing.py]
    N117[__init__.py]
    N118[sales_forecast.js]
    N119[sales_forecast.py]
    N120[sales_forecast_dashboard.py]
    N121[sales_forecast_list.js]
    N122[test_sales_forecast.py]
    N123[__init__.py]
    N124[sales_forecast_item.py]
    N125[__init__.py]
    N126[sub_operation.js]
    N127[sub_operation.py]
    N128[test_sub_operation.py]
    N129[__init__.py]
    N130[test_work_order.py]
    N131[work_order.js]
    N132[work_order.py]
    N133[work_order_calendar.js]
    N134[work_order_dashboard.py]
    N135[work_order_list.js]
    N136[__init__.py]
    N137[work_order_item.py]
    N138[__init__.py]
    N139[work_order_operation.py]
    N140[__init__.py]
    N141[_test_workstation.js]
    N142[test_workstation.py]
    N143[workstation.js]
    N144[workstation.py]
    N145[workstation_dashboard.py]
    N146[workstation_list.js]
    N147[__init__.py]
    N148[test_workstation_cost.py]
    N149[workstation_cost.js]
    N150[workstation_cost.py]
    N151[__init__.py]
    N152[test_workstation_operating_component.py]
    N153[workstation_operating_component.js]
    N154[workstation_operating_component.py]
    N155[__init__.py]
    N156[test_workstation_operating_component_account.py]
    N157[workstation_operating_component_account.js]
    N158[workstation_operating_component_account.py]
    N159[__init__.py]
    N160[test_workstation_type.py]
    N161[workstation_type.js]
    N162[workstation_type.py]
    N163[__init__.py]
    N164[workstation_working_hour.py]
    N165[__init__.py]
    N166[__init__.py]
    N167[material_request_receipt_notification.py]
    N168[__init__.py]
    N169[__init__.py]
    N170[bom_comparison_tool.js]
    N171[__init__.py]
    N172[visual_plant_floor.js]
    N173[__init__.py]
    N174[__init__.py]
    N175[bom_explorer.js]
    N176[bom_explorer.py]
    N177[__init__.py]
    N178[bom_operations_time.js]
    N179[bom_operations_time.py]
    N180[__init__.py]
    N181[bom_stock_calculated.js]
    N182[bom_stock_calculated.py]
    N183[test_bom_stock_calculated.py]
    N184[__init__.py]
    N185[bom_stock_report.js]
    N186[bom_stock_report.py]
    N187[test_bom_stock_report.py]
    N188[__init__.py]
    N189[bom_variance_report.js]
    N190[bom_variance_report.py]
    N191[__init__.py]
    N192[__init__.py]
    N193[cost_of_poor_quality_report.js]
    N194[cost_of_poor_quality_report.py]
    N195[__init__.py]
    N196[downtime_analysis.js]
    N197[downtime_analysis.py]
    N198[__init__.py]
    N199[exponential_smoothing_forecasting.js]
    N200[exponential_smoothing_forecasting.py]
    N201[__init__.py]
    N202[__init__.py]
    N203[job_card_summary.js]
    N204[job_card_summary.py]
    N205[__init__.py]
    N206[material_requirements_planning_report.js]
    N207[material_requirements_planning_report.py]
    N208[__init__.py]
    N209[__init__.py]
    N210[process_loss_report.js]
    N211[process_loss_report.py]
    N212[__init__.py]
    N213[production_analytics.js]
    N214[production_analytics.py]
    N215[__init__.py]
    N216[production_plan_summary.js]
    N217[production_plan_summary.py]
    N218[__init__.py]
    N219[production_planning_report.js]
    N220[production_planning_report.py]
    N221[__init__.py]
    N222[quality_inspection_summary.js]
    N223[quality_inspection_summary.py]
    N224[test_reports.py]
    N225[__init__.py]
    N226[work_order_consumed_materials.js]
    N227[work_order_consumed_materials.py]
    N228[__init__.py]
    N229[work_order_stock_report.js]
    N230[work_order_stock_report.py]
    N231[__init__.py]
    N232[work_order_summary.js]
    N233[work_order_summary.py]
    N234[__init__.py]