graph TD
    N0[__init__.py]
    N1[dashboard_fixtures.py]
    N2[__init__.py]
    N3[__init__.py]
    N4[asset.js]
    N5[asset.py]
    N6[asset_dashboard.py]
    N7[asset_list.js]
    N8[depreciation.py]
    N9[test_asset.py]
    N10[__init__.py]
    N11[asset_activity.js]
    N12[asset_activity.py]
    N13[test_asset_activity.py]
    N14[__init__.py]
    N15[asset_capitalization.js]
    N16[asset_capitalization.py]
    N17[test_asset_capitalization.py]
    N18[__init__.py]
    N19[asset_capitalization_asset_item.py]
    N20[__init__.py]
    N21[asset_capitalization_service_item.py]
    N22[__init__.py]
    N23[asset_capitalization_stock_item.py]
    N24[__init__.py]
    N25[asset_category.js]
    N26[asset_category.py]
    N27[test_asset_category.py]
    N28[__init__.py]
    N29[asset_category_account.py]
    N30[__init__.py]
    N31[asset_depreciation_schedule.js]
    N32[asset_depreciation_schedule.py]
    N33[deppreciation_schedule_controller.py]
    N34[depreciation_methods.py]
    N35[test_asset_depreciation_schedule.py]
    N36[__init__.py]
    N37[asset_finance_book.py]
    N38[__init__.py]
    N39[asset_maintenance.js]
    N40[asset_maintenance.py]
    N41[test_asset_maintenance.py]
    N42[__init__.py]
    N43[asset_maintenance_log.js]
    N44[asset_maintenance_log.py]
    N45[asset_maintenance_log_calendar.js]
    N46[asset_maintenance_log_list.js]
    N47[test_asset_maintenance_log.py]
    N48[__init__.py]
    N49[asset_maintenance_task.py]
    N50[__init__.py]
    N51[asset_maintenance_team.js]
    N52[asset_maintenance_team.py]
    N53[test_asset_maintenance_team.py]
    N54[__init__.py]
    N55[asset_movement.js]
    N56[asset_movement.py]
    N57[test_asset_movement.py]
    N58[__init__.py]
    N59[asset_movement_item.py]
    N60[__init__.py]
    N61[asset_repair.js]
    N62[asset_repair.py]
    N63[asset_repair_list.js]
    N64[test_asset_repair.py]
    N65[__init__.py]
    N66[asset_repair_consumed_item.py]
    N67[__init__.py]
    N68[asset_repair_purchase_invoice.py]
    N69[__init__.py]
    N70[asset_shift_allocation.js]
    N71[asset_shift_allocation.py]
    N72[test_asset_shift_allocation.py]
    N73[__init__.py]
    N74[asset_shift_factor.js]
    N75[asset_shift_factor.py]
    N76[test_asset_shift_factor.py]
    N77[__init__.py]
    N78[asset_value_adjustment.js]
    N79[asset_value_adjustment.py]
    N80[test_asset_value_adjustment.py]
    N81[__init__.py]
    N82[depreciation_schedule.py]
    N83[__init__.py]
    N84[linked_location.py]
    N85[__init__.py]
    N86[location.js]
    N87[location.py]
    N88[location_tree.js]
    N89[test_location.py]
    N90[__init__.py]
    N91[maintenance_team_member.js]
    N92[maintenance_team_member.py]
    N93[test_maintenance_team_member.py]
    N94[__init__.py]
    N95[__init__.py]
    N96[__init__.py]
    N97[__init__.py]
    N98[fixed_asset_register.js]
    N99[fixed_asset_register.py]