graph TD
    N0[__init__.py]
    N1[__init__.py]
    N2[__init__.py]
    N3[buying_settings.js]
    N4[buying_settings.py]
    N5[test_buying_settings.py]
    N6[__init__.py]
    N7[customer_number_at_supplier.py]
    N8[__init__.py]
    N9[purchase_order.js]
    N10[purchase_order.py]
    N11[purchase_order_dashboard.py]
    N12[purchase_order_list.js]
    N13[test_purchase_order.py]
    N14[__init__.py]
    N15[purchase_order_item.py]
    N16[__init__.py]
    N17[purchase_order_item_supplied.py]
    N18[__init__.py]
    N19[purchase_receipt_item_supplied.py]
    N20[__init__.py]
    N21[request_for_quotation.js]
    N22[request_for_quotation.py]
    N23[request_for_quotation_dashboard.py]
    N24[test_request_for_quotation.py]
    N25[__init__.py]
    N26[request_for_quotation_item.py]
    N27[__init__.py]
    N28[request_for_quotation_supplier.py]
    N29[__init__.py]
    N30[__init__.py]
    N31[migrate_supplier_portal_users.py]
    N32[supplier.js]
    N33[supplier.py]
    N34[supplier_dashboard.py]
    N35[supplier_list.js]
    N36[test_supplier.py]
    N37[__init__.py]
    N38[supplier_quotation.js]
    N39[supplier_quotation.py]
    N40[supplier_quotation_dashboard.py]
    N41[supplier_quotation_list.js]
    N42[test_supplier_quotation.py]
    N43[__init__.py]
    N44[supplier_quotation_item.py]
    N45[__init__.py]
    N46[supplier_scorecard.js]
    N47[supplier_scorecard.py]
    N48[supplier_scorecard_dashboard.py]
    N49[supplier_scorecard_list.js]
    N50[test_supplier_scorecard.py]
    N51[__init__.py]
    N52[supplier_scorecard_criteria.js]
    N53[supplier_scorecard_criteria.py]
    N54[test_supplier_scorecard_criteria.py]
    N55[__init__.py]
    N56[supplier_scorecard_period.js]
    N57[supplier_scorecard_period.py]
    N58[test_supplier_scorecard_period.py]
    N59[__init__.py]
    N60[supplier_scorecard_scoring_criteria.py]
    N61[__init__.py]
    N62[supplier_scorecard_scoring_standing.py]
    N63[__init__.py]
    N64[supplier_scorecard_scoring_variable.py]
    N65[__init__.py]
    N66[supplier_scorecard_standing.js]
    N67[supplier_scorecard_standing.py]
    N68[test_supplier_scorecard_standing.py]
    N69[__init__.py]
    N70[supplier_scorecard_variable.js]
    N71[supplier_scorecard_variable.py]
    N72[test_supplier_scorecard_variable.py]
    N73[__init__.py]
    N74[__init__.py]
    N75[__init__.py]
    N76[__init__.py]
    N77[__init__.py]
    N78[__init__.py]
    N79[__init__.py]
    N80[__init__.py]
    N81[__init__.py]
    N82[__init__.py]
    N83[item_wise_purchase_history.js]
    N84[item_wise_purchase_history.py]
    N85[__init__.py]
    N86[procurement_tracker.js]
    N87[procurement_tracker.py]
    N88[test_procurement_tracker.py]
    N89[__init__.py]
    N90[purchase_analytics.js]
    N91[purchase_analytics.py]
    N92[__init__.py]
    N93[purchase_order_analysis.js]
    N94[purchase_order_analysis.py]
    N95[__init__.py]
    N96[purchase_order_trends.js]
    N97[purchase_order_trends.py]
    N98[__init__.py]
    N99[requested_items_to_order_and_receive.js]
    N100[requested_items_to_order_and_receive.py]
    N101[test_requested_items_to_order_and_receive.py]
    N102[__init__.py]
    N103[subcontract_order_summary.js]
    N104[subcontract_order_summary.py]
    N105[__init__.py]
    N106[subcontracted_item_to_be_received.js]
    N107[subcontracted_item_to_be_received.py]
    N108[test_subcontracted_item_to_be_received.py]
    N109[__init__.py]
    N110[subcontracted_raw_materials_to_be_transferred.js]
    N111[subcontracted_raw_materials_to_be_transferred.py]
    N112[test_subcontracted_raw_materials_to_be_transferred.py]
    N113[__init__.py]
    N114[supplier_quotation_comparison.js]
    N115[supplier_quotation_comparison.py]
    N116[utils.py]