graph TD
    N0[__init__.py]
    N1[data_import.js]
    N2[data_import.py]
    N3[data_import_list.js]
    N4[exporter.py]
    N5[importer.py]
    N6[__init__.py]
    N7[remove_stale_docfields_from_legacy_version.py]
    N8[test_data_import.py]
    N9[test_exporter.py]
    N10[test_importer.py]