graph TD
    N0[__init__.py]
    N1[__init__.py]
    N2[__init__.py]
    N3[activity_cost.js]
    N4[activity_cost.py]
    N5[test_activity_cost.py]
    N6[__init__.py]
    N7[activity_type.js]
    N8[activity_type.py]
    N9[test_activity_type.py]
    N10[__init__.py]
    N11[dependent_task.py]
    N12[__init__.py]
    N13[project.js]
    N14[project.py]
    N15[project_dashboard.py]
    N16[project_list.js]
    N17[project_timesheet.js]
    N18[test_project.py]
    N19[__init__.py]
    N20[project_template.js]
    N21[project_template.py]
    N22[project_template_dashboard.py]
    N23[test_project_template.py]
    N24[__init__.py]
    N25[project_template_task.py]
    N26[__init__.py]
    N27[project_type.js]
    N28[project_type.py]
    N29[test_project_type.py]
    N30[__init__.py]
    N31[project_update.js]
    N32[project_update.py]
    N33[test_project_update.py]
    N34[__init__.py]
    N35[project_user.py]
    N36[__init__.py]
    N37[projects_settings.js]
    N38[projects_settings.py]
    N39[test_projects_settings.py]
    N40[__init__.py]
    N41[task.js]
    N42[task.py]
    N43[task_calendar.js]
    N44[task_dashboard.py]
    N45[task_list.js]
    N46[task_tree.js]
    N47[test_task.py]
    N48[__init__.py]
    N49[task_depends_on.py]
    N50[__init__.py]
    N51[task_type.js]
    N52[task_type.py]
    N53[test_task_type.py]
    N54[__init__.py]
    N55[test_timesheet.py]
    N56[timesheet.js]
    N57[timesheet.py]
    N58[timesheet_calendar.js]
    N59[timesheet_dashboard.py]
    N60[timesheet_list.js]
    N61[__init__.py]
    N62[timesheet_detail.py]
    N63[__init__.py]
    N64[__init__.py]
    N65[daily_timesheet_summary.js]
    N66[daily_timesheet_summary.py]
    N67[__init__.py]
    N68[delayed_tasks_summary.js]
    N69[delayed_tasks_summary.py]
    N70[test_delayed_tasks_summary.py]
    N71[__init__.py]
    N72[project_summary.js]
    N73[project_summary.py]
    N74[__init__.py]
    N75[project_wise_stock_tracking.js]
    N76[project_wise_stock_tracking.py]
    N77[__init__.py]
    N78[timesheet_billing_summary.js]
    N79[timesheet_billing_summary.py]
    N80[utils.py]
    N81[__init__.py]
    N82[__init__.py]
    N83[tasks.js]
    N84[tasks.py]