<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by DINHDT (SEATECH) -->
<xs:schema xmlns="http://kekhaithue.gdt.gov.vn/TKhaiThue" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://kekhaithue.gdt.gov.vn/TKhaiThue" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.1.5">
	<xs:redefine schemaLocation="../TKhaiThue.xsd">
		<xs:complexType name="CTieuTKhaiChinhType">
			<xs:complexContent>
				<xs:extension base="CTieuTKhaiChinhType">
					<xs:sequence>
						<xs:element name="Header">
							<xs:annotation>
								<xs:documentation>Thông tin chung</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="maXa" type="xs:string">
										<xs:annotation>
											<xs:documentation>Mã xã</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="tenXa" type="xs:string">
										<xs:annotation>
											<xs:documentation>Tên xã</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="maLoaiHoan" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Mã loại hoàn thuế</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="tenLoaiHoan" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Tên loại hoàn thuế</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="so" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Số giấy đề nghị hoàn</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="diaDiem" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>..., ngày ... tháng ... năm ...</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="ngay" type="xs:date" nillable="true">
										<xs:annotation>
											<xs:documentation>ngày ... tháng ... năm ...</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="maCoQuanThu" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Kính gửi: .......(mã cơ quan thu, cơ quan có thẩm quyền hoàn trả)........ </xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="tenCoQuanThu" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Kính gửi: .......(tên cơ quan thu, cơ quan có thẩm quyền hoàn trả)........</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="soCMND_HoChieu" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>CMND/Hộ chiếu số </xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="ngayCap" type="xs:date" nillable="true">
										<xs:annotation>
											<xs:documentation>Ngày cấp:........./......./.........</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="noiCap" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Nơi cấp</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="quocTich" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Quốc tịch </xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="donViTien_ma" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Mã đơn vị tiền </xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="donViTien_ten" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Tên đơn vị tiền</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="maHoSoKhaiDuAnDauTu" type="xs:string" nillable="true">
							<xs:annotation>
								<xs:documentation>Mã hồ sơ khai dự án đầu tư</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="ngayHoanThanhDuAn" type="xs:date" nillable="true">
							<xs:annotation>
								<xs:documentation>Ngày hoàn thành dự án</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="cqtQLyNoiCoDADT">
							<xs:annotation>
								<xs:documentation>Cơ quan thuế quản lý nơi có DAĐT</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="maCQT" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Mã cơ quan thuế</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="tenCoQuanthue" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Tên cơ quan thuế</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="TTDuAnDauTu">
							<xs:annotation>
								<xs:documentation>Hàng hoá, dịch vụ mua vào trong kỳ</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="tenDuAn" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Tên dự án</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="diaChiThucHienDuAn" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Địa chỉ thực hiện dự án</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="chuDuAnDauTu" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Chủ dự án đầu tư</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="maSoThueDuAnDauTu" type="TINType" nillable="true">
										<xs:annotation>
											<xs:documentation>MST chủ dự án đầu tư</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="VBPheDuyetDuAnDauTu">
							<xs:annotation>
								<xs:documentation>Văn bản phê duyệt dự án đầu tư</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="so" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Số văn bản</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="ngay" type="xs:date" nillable="true">
										<xs:annotation>
											<xs:documentation>Ngày ban hành văn bản phê  duyệt dự án đầu tư</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="coQuanBanHanhPheDuyetDADT" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Cơ quan ban hành văn bản phê duyệt dự án đầu tư</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="NoiDungDNHT">
							<xs:annotation>
								<xs:documentation>II- Nội dung đề nghị hoàn trả khoản thu ngân sách nhà nước (NSNN)</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="TTinDNHT">
										<xs:annotation>
											<xs:documentation>1. Thông tin về khoản thu đề nghị hoàn trả</xs:documentation>
										</xs:annotation>
										<xs:complexType>
											<xs:sequence>
												<xs:element name="CTietTTinDNHT" maxOccurs="unbounded">
													<xs:annotation>
														<xs:documentation>Bảng kê thông tin về khoản thu đề nghị hoàn trả</xs:documentation>
													</xs:annotation>
													<xs:complexType>
														<xs:sequence>
															<xs:element name="ct2_ma" type="xs:string" nillable="true">
																<xs:annotation>
																	<xs:documentation>Mã loại thuế</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct2_ten" type="xs:string" nillable="true">
																<xs:annotation>
																	<xs:documentation>Tên loại thuế</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct3_TuKy_LoaiKy">
																<xs:annotation>
																	<xs:documentation>Chọn Tháng M, Quý Q, Năm Y</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:element>
															<xs:element name="ct3_TuKy_KyKeKhai" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Quý: Q/YYYY, tháng: MM/YYYY, năm: YYYY</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct3_TuKy_kyKKhaiTuNgay" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Định dạng DD/MM/YYYY</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct3_TuKy_kyKKhaiDenNgay" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Định dạng DD/MM/YYYY</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct3_TuKy_kyKKhaiTuThang" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Định dạng MM/YYYY</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct3_TuKy_kyKKhaiDenThang" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Định dạng MM/YYYY</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct4_DenKy_LoaiKy">
																<xs:annotation>
																	<xs:documentation>Chọn Tháng M, Quý Q, Năm Y</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:element>
															<xs:element name="ct4_DenKy_KyKeKhai" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Quý: Q/YYYY, tháng: MM/YYYY, năm: YYYY</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct4_DenKy_kyKKhaiTuNgay" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Định dạng DD/MM/YYYY</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct4_DenKy_kyKKhaiDenNgay" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Định dạng DD/MM/YYYY</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct4_DenKy_kyKKhaiTuThang" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Định dạng MM/YYYY</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct4_DenKy_kyKKhaiDenThang" type="xs:string">
																<xs:annotation>
																	<xs:documentation>Định dạng MM/YYYY</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="maGiaoDich" type="xs:string" nillable="true">
																<xs:annotation>
																	<xs:documentation>Mã giao dịch điện tử của hồ sơ khai thuế đề nghị hoàn </xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct6" type="xs:decimal" nillable="true">
																<xs:annotation>
																	<xs:documentation>Số tiền đề nghị hoàn trong kỳ (VNĐ)</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct7_ma" type="xs:string" nillable="true">
																<xs:annotation>
																	<xs:documentation>Trường hợp đề nghị hoàn thuế</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct7_ten" type="xs:string" nillable="true">
																<xs:annotation>
																	<xs:documentation>Trường hợp đề nghị hoàn thuế</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="ct8" type="xs:string" nillable="true">
																<xs:annotation>
																	<xs:documentation>Ghi chú</xs:documentation>
																</xs:annotation>
															</xs:element>
														</xs:sequence>
														<xs:attribute name="id" type="xs:string"/>
													</xs:complexType>
												</xs:element>
												<xs:element name="tongCot6" type="xs:decimal" nillable="true">
													<xs:annotation>
														<xs:documentation>Tổng Cộng </xs:documentation>
													</xs:annotation>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="HThucDNHT">
										<xs:annotation>
											<xs:documentation>2. Hình thức đề nghị hoàn trả</xs:documentation>
										</xs:annotation>
										<xs:complexType>
											<xs:sequence>
												<xs:element name="BuTruChoKhoanPNop">
													<xs:annotation>
														<xs:documentation>2.1. Bù trừ cho khoản phải nộp NSNN </xs:documentation>
													</xs:annotation>
													<xs:complexType>
														<xs:sequence>
															<xs:element name="CTietBuTru" maxOccurs="unbounded">
																<xs:annotation>
																	<xs:documentation>Bảng kê bù trừ cho khoản phải nộp NSNN</xs:documentation>
																</xs:annotation>
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="mst" type="TINType" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mã số thuế</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct3" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mã định danh khoản phải nộp (nếu có)</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct4_ma" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mã Cơ quan thuế</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct4_ten" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên Cơ quan thuế</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct5_ma" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mã Nội dung kinh tế (tiểu mục)</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct5_ten" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên Nội dung kinh tế (tiểu mục)</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct6_LoaiKy">
																			<xs:annotation>
																				<xs:documentation>Chọn Tháng M, Quý Q, Năm Y, lần phát sinh D</xs:documentation>
																			</xs:annotation>
																			<xs:simpleType>
																				<xs:restriction base="xs:string"/>
																			</xs:simpleType>
																		</xs:element>
																		<xs:element name="ct6_KyKeKhai" type="xs:string">
																			<xs:annotation>
																				<xs:documentation>Quý: Q/YYYY, tháng: MM/YYYY, năm: YYYY, lần phát sinh: DD/MM/YYYY</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct6_kyKKhaiTuNgay" type="xs:string">
																			<xs:annotation>
																				<xs:documentation>Định dạng DD/MM/YYYY</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct6_kyKKhaiDenNgay" type="xs:string">
																			<xs:annotation>
																				<xs:documentation>Định dạng DD/MM/YYYY</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct6_kyKKhaiTuThang" type="xs:string">
																			<xs:annotation>
																				<xs:documentation>Định dạng MM/YYYY</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct6_kyKKhaiDenThang" type="xs:string">
																			<xs:annotation>
																				<xs:documentation>Định dạng MM/YYYY</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct7" type="xs:decimal" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Số tiền đề nghị bù trừ (VNĐ)</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct8_ma" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mã Ghi chú</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct8_ten" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên Ghi chú</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ct8_Khac" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Ghi chú: Khác</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																	</xs:sequence>
																	<xs:attribute name="id" type="xs:string"/>
																</xs:complexType>
															</xs:element>
															<xs:element name="tongCot7" type="xs:decimal" nillable="true">
																<xs:annotation>
																	<xs:documentation>Tổng cộng số tiền</xs:documentation>
																</xs:annotation>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="HoanTraTrucTiep">
													<xs:annotation>
														<xs:documentation>2.2. Hoàn trả trực tiếp </xs:documentation>
													</xs:annotation>
													<xs:complexType>
														<xs:sequence>
															<xs:element name="HinhThucHoanTra">
																<xs:annotation>
																	<xs:documentation>Hình thức hoàn trả</xs:documentation>
																</xs:annotation>
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="chuyenKhoan" type="xs:boolean" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Chuyển khoản</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tenChuTaiKhoan" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên chủ tài khoản</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="taiKhoanSo" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tài khoản số</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="taiNganHang_ma" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>mã Ngân hàng (KBNN).......</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="taiNganHang_ten" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên Ngân hàng (KBNN).......</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tienMat" type="xs:boolean" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tiền mặt</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="nguoiNhanTien" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên người nhận tiền</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="cmt-HoChieu" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Chứng minh thư (Hộ chiếu)</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ngayCap" type="xs:date" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Ngày cấp</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tinh-ThanhPho_ma" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mã Tỉnh (Thành phố) </xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tinh-ThanhPho_ten" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên Tỉnh (Thành phố) </xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="noiNhanTien" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Nơi nhận tiền hoàn thuế: Kho bạc Nhà nước </xs:documentation>
																			</xs:annotation>
																		</xs:element>
																	</xs:sequence>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="TaiLieuGuiKem">
							<xs:annotation>
								<xs:documentation>III- Tài liệu gửi kèm</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="TaiLieu" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="maTaiLieu" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Mã tài liệu</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="tenTaiLieu" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Tên tài liệu</xs:documentation>
													</xs:annotation>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
		<xs:complexType name="PLucType">
			<xs:complexContent>
				<xs:extension base="PLucType">
					<xs:sequence>
						<xs:element name="PLuc_01_1_HT" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="HoaDonChungTuNopThue" nillable="true" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="mauSo" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Hoá đơn, chứng từ nộp thuế: Mẫu số</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="kyHieu" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Hoá đơn, chứng từ nộp thuế: Ký hiệu</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="so" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Hoá đơn, chứng từ nộp thuế: Số</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ngayThangNam" type="xs:date" nillable="true">
													<xs:annotation>
														<xs:documentation>Hoá đơn, chứng từ nộp thuế: Ngày Tháng Năm</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="tenNguoiBan" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Tên người bán</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="mstNguoiBan" type="TINType" nillable="true">
													<xs:annotation>
														<xs:documentation>MST người bán</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="tenHHDV" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Tên hàng hóa, dịch vụ </xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="donViTinh" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Đơn vị tính</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="soLuong" type="xs:decimal" nillable="true">
													<xs:annotation>
														<xs:documentation>Số lượng</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="donGia" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Đơn giá</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="giaTriHHDV" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Giá trị HHDV
mua vào chưa có thuế GTGT</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="thueSuat" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thuế suất
(%)</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="tienThueGTGT" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Tiền thuế GTGT</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ghiChu" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Ghi chú</xs:documentation>
													</xs:annotation>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="id" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="tongCong" type="xs:long" nillable="true">
										<xs:annotation>
											<xs:documentation>Tổng cộng Tiền thuế GTGT</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="PLuc_01_2_HT" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ToKhaiHangHoaXuatKhau" nillable="true" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="maLoaiHinh" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Mã loại hình</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="tenLoaiHinh" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Tên loại hình</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="toKhaiSo" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Tờ khai số</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ngayDangKy" type="xs:date" nillable="true">
													<xs:annotation>
														<xs:documentation>Ngày đăng ký</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ma_NuocNhapKhau" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Mã nước nhập khẩu</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ten_NuocNhapKhau" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Tên nước nhập khẩu</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ma_Loaitien" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Mã loại tiền</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ten_Loaitien" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Tên loại tiền</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ngoaiTe" type="xs:decimal" nillable="true">
													<xs:annotation>
														<xs:documentation>Trị giá: Ngoại tệ </xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="dongVietNam" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Trị giá: Đồng Việt Nam</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ghiChu" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Ghi chú</xs:documentation>
													</xs:annotation>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="id" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="PLuc_01_4_HT" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="BangKeChungTuHoan" nillable="true" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="kyHieu" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hóa đơn: Ký hiệu</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="soHoaDon" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hóa đơn: Số</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ngayThangNam" type="xs:date" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hóa đơn: Ngày Tháng Năm</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="tenDonViBanHang" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin doanh nghiệp bán hàng: Tên đơn vị bán hàng</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="mstNguoiBan" type="TINType" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin doanh nghiệp bán hàng: MST</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="hoVaTen" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin về người nước ngoài: Họ và tên</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="so" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin về người nước ngoài/Hộ chiếu/Giấy tờ nhập xuất cảnh: Số</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ngayCap" type="xs:date" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin về người nước ngoài/Hộ chiếu/Giấy tờ nhập xuất cảnh: Ngày cấp</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ma_QuocTich" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin về người nước ngoài/Hộ chiếu/Giấy tờ nhập xuất cảnh: Mã quốc tịch</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ten_QuocTich" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin về người nước ngoài/Hộ chiếu/Giấy tờ nhập xuất cảnh: Tên quốc tịch</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="triGiaHangChuaThueGTGT" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hàng hóa: Trị giá hàng chưa thuế GTGT</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="thueGTGT" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hàng hóa: thuế GTGT</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="maCQHQ" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hoàn thuế: Mã cơ quan hải quan xác nhận </xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="tenCQHQ" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hoàn thuế: Tên cơ quan hải quan xác nhận </xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ngayNHHoan" type="xs:date" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hoàn thuế: Ngày ngân hàng hoàn thuế cho người nước ngoài </xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="soTienThueGTGT" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hoàn thuế: Số tiền thuế GTGT ngân hàng đã ứng trước để hoàn cho người nước ngoài</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="phiDichVu" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hoàn thuế: Phí dịch vụ ngân hàng được hưởng </xs:documentation>
													</xs:annotation>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="id" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="tongCongTriGiaHangChuaThueGTGT" type="xs:long" nillable="true">
										<xs:annotation>
											<xs:documentation>Tổng cộng Trị giá hàng chưa thuế GTGT</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="tongCongThueGTGT" type="xs:long" nillable="true">
										<xs:annotation>
											<xs:documentation>Tổng cộng Thuế GTGT</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="tongCongSoTienThueGTGT" type="xs:long" nillable="true">
										<xs:annotation>
											<xs:documentation>Tổng cộng Số tiền thuế GTGT ngân hàng đã ứng trước để hoàn cho người nước ngoài</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="tongCongPhiDichVu" type="xs:long" nillable="true">
										<xs:annotation>
											<xs:documentation>Tổng cộng Phí dịch vụ ngân hàng được hưởng</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="tongSoTienDeNghiHoanTra" type="xs:long" nillable="true">
										<xs:annotation>
											<xs:documentation>Tổng cộng Tổng số tiền đề nghị hoàn trả</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="PLuc_01_3a_HT" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="quy" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Hàng hóa, dịch vụ hoặc xăng xe mua trong quý</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="nam" type="xs:string" nillable="true">
										<xs:annotation>
											<xs:documentation>Hàng hóa, dịch vụ hoặc xăng xe mua trong quý....năm</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="BangKeGTGT">
										<xs:annotation>
											<xs:documentation>Hàng hoá, dịch vụ dùng cho cơ quan hoặc xăng dùng cho xe cơ quan (Goods, services and petrol for official use)</xs:documentation>
										</xs:annotation>
										<xs:complexType>
											<xs:sequence>
												<xs:element name="HHDV_XANGDUNGCQ">
													<xs:annotation>
														<xs:documentation>I. Hàng hoá, dịch vụ dùng cho cơ quan hoặc xăng dùng cho xe cơ quan (Goods, services and petrol for official use)</xs:documentation>
													</xs:annotation>
													<xs:complexType>
														<xs:sequence>
															<xs:element name="HHDVDUNGCOQUAN" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="mauSo" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mẫu số</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="kyHieu" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>ký hiệu</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="so" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>số</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ngayThangNam" type="xs:date" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Đơn vị tính</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tenNCC" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên Nhà cung cấp</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="mstNCC" type="TINType" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mã số thuế nhà cung cấp</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tenHHDV" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên hàng hóa dich vụ</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="donViTinh" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Đơn vị tính</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="soLuong" type="xs:decimal" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Số lượng</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="doanhSo" type="xs:long" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Doanh số mua chưa thuế GTGT</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tienThueGTGT" type="xs:long" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tiền thuế GTGT</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																	</xs:sequence>
																	<xs:attribute name="id" type="xs:string"/>
																</xs:complexType>
															</xs:element>
															<xs:element name="XANGDUNGCOQUAN" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="mauSo" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mẫu số</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="kyHieu" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>ký hiệu</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="so" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>số</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ngayThangNam" type="xs:date" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Đơn vị tính</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tenNCC" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên Nhà cung cấp</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="mstNCC" type="TINType" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mã số thuế nhà cung cấp</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tenHHDV" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên hàng hóa dich vụ</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="donViTinh" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Đơn vị tính</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="soLuong" type="xs:decimal" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Số lượng</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="doanhSo" type="xs:long" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Doanh số mua chưa thuế GTGT</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tienThueGTGT" type="xs:long" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tiền thuế GTGT</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																	</xs:sequence>
																	<xs:attribute name="id" type="xs:string"/>
																</xs:complexType>
															</xs:element>
															<xs:element name="tongCong_ct11" type="xs:long" nillable="true">
																<xs:annotation>
																	<xs:documentation>Tổng cộng Doanh số mua chưa có thuế GTGT
(Purchased price without
VAT)
</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="tongCong_ct12" type="xs:long" nillable="true">
																<xs:annotation>
																	<xs:documentation>Tiền thuế GTGT
(Refundable
tax)
</xs:documentation>
																</xs:annotation>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="HHDV_XANGDUNGCANHAN">
													<xs:annotation>
														<xs:documentation>II.Hàng hoá, dịch vụ dùng cho cá nhân hoặc xăng dùng cho xe cá nhân của viên chức ngoại giao ....(***) (Goods, services or petrol for personal use of diplomatic agent </xs:documentation>
													</xs:annotation>
													<xs:complexType>
														<xs:sequence>
															<xs:element name="HHDVDUNGCANHAN" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="mauSo" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mẫu số</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="kyHieu" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>ký hiệu</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="so" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>số</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ngayThangNam" type="xs:date" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Đơn vị tính</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tenNCC" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên Nhà cung cấp</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="mstNCC" type="TINType" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mã số thuế nhà cung cấp</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tenHHDV" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên hàng hóa dich vụ</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="donViTinh" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Đơn vị tính</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="soLuong" type="xs:decimal" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Số lượng</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="doanhSo" type="xs:long" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Doanh số mua chưa thuế GTGT</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tienThueGTGT" type="xs:long" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tiền thuế GTGT</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																	</xs:sequence>
																	<xs:attribute name="id" type="xs:string"/>
																</xs:complexType>
															</xs:element>
															<xs:element name="XANGDUNGCANHAN" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="mauSo" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mẫu số</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="kyHieu" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>ký hiệu</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="so" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>số</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="ngayThangNam" type="xs:date" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Đơn vị tính</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tenNCC" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên Nhà cung cấp</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="mstNCC" type="TINType" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Mã số thuế nhà cung cấp</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tenHHDV" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tên hàng hóa dich vụ</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="donViTinh" type="xs:string" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Đơn vị tính</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="soLuong" type="xs:decimal" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Số lượng</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="doanhSo" type="xs:long" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Doanh số mua chưa thuế GTGT</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																		<xs:element name="tienThueGTGT" type="xs:long" nillable="true">
																			<xs:annotation>
																				<xs:documentation>Tiền thuế GTGT</xs:documentation>
																			</xs:annotation>
																		</xs:element>
																	</xs:sequence>
																	<xs:attribute name="id" type="xs:string"/>
																</xs:complexType>
															</xs:element>
															<xs:element name="tongCong_ct11" type="xs:long" nillable="true">
																<xs:annotation>
																	<xs:documentation>Tổng cộng Doanh số mua chưa có thuế GTGT
(Purchased price without
VAT)
</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="tongCong_ct12" type="xs:long" nillable="true">
																<xs:annotation>
																	<xs:documentation>Tiền thuế GTGT
(Refundable
tax)
</xs:documentation>
																</xs:annotation>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="tongCong_ct11" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Tổng cộng I+II: Doanh số mua chưa có thuế GTGT
(Purchased price without
VAT)</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="tongCong_ct12" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Tổng cộng I+II :Tiền thuế GTGT
(Refundable
tax)</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="HinhThucHoanTra">
													<xs:annotation>
														<xs:documentation>Hình thức hoàn trả</xs:documentation>
													</xs:annotation>
													<xs:complexType>
														<xs:sequence>
															<xs:element name="tenChuTaiKhoan" type="xs:string" nillable="true">
																<xs:annotation>
																	<xs:documentation>Tên chủ tài khoản</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="taiKhoanSo" type="xs:string" nillable="true">
																<xs:annotation>
																	<xs:documentation>Tài khoản số</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="NganHang_ma" type="xs:string" nillable="true">
																<xs:annotation>
																	<xs:documentation>mã Ngân hàng (KBNN).......</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="NganHang_ten" type="xs:string" nillable="true">
																<xs:annotation>
																	<xs:documentation>Tên Ngân hàng (KBNN).......</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="soTien" type="xs:long" nillable="true">
																<xs:annotation>
																	<xs:documentation>Số tiền</xs:documentation>
																</xs:annotation>
															</xs:element>
															<xs:element name="soTienHoanCahan" type="xs:long" nillable="true">
																<xs:annotation>
																	<xs:documentation>b, Hoàn thuế GTGT cho hàng hoá, dịch vụ hoặc xăng xe dùng cho cá nhân của viên chức ngoại giao: Số tiền</xs:documentation>
																</xs:annotation>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="PLuc_01_3b_HT" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="VienChucNgoaiGiaoHoanThue" nillable="true" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="tenCaNhan" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Tên cá nhân</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="chucVu" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Chức vụ</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="so" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hộ chiếu : Số</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ngayCap" type="xs:date" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hộ chiếu : Ngày cấp</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ngayHetHan" type="xs:date" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hộ chiếu : Ngày hết hạn</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ma_QuocTich" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hộ chiếu: Mã quốc tịch</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="ten_QuocTich" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Thông tin hộ chiếu: Tên quốc tịch</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="soTaiKhoan" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Ghi chú</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="tenChuTaiKhoan" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Ghi chú</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="NganHang_ma" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>mã Ngân hàng (KBNN).......</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="NganHang_ten" type="xs:string" nillable="true">
													<xs:annotation>
														<xs:documentation>Tên Ngân hàng (KBNN).......</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="soTienThueGTGTDeNghiHoan" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Tên Ngân hàng (KBNN).......</xs:documentation>
													</xs:annotation>
												</xs:element>
												<xs:element name="soTienThueGTGTXacNhanHoan" type="xs:long" nillable="true">
													<xs:annotation>
														<xs:documentation>Tên Ngân hàng (KBNN).......</xs:documentation>
													</xs:annotation>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="id" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:redefine>
</xs:schema>
