graph TD
    N0[__init__.py]
    N1[__init__.py]
    N2[__init__.py]
    N3[connected_app.js]
    N4[connected_app.py]
    N5[test_connected_app.py]
    N6[__init__.py]
    N7[geolocation_settings.js]
    N8[geolocation_settings.py]
    N9[geoapify.py]
    N10[here.py]
    N11[nomatim.py]
    N12[test_geolocation_settings.py]
    N13[__init__.py]
    N14[google_calendar.js]
    N15[google_calendar.py]
    N16[__init__.py]
    N17[google_contacts.js]
    N18[google_contacts.py]
    N19[test_google_contacts.py]
    N20[__init__.py]
    N21[google_settings.js]
    N22[google_settings.py]
    N23[test_google_settings.py]
    N24[__init__.py]
    N25[integration_request.js]
    N26[integration_request.py]
    N27[integration_request_list.js]
    N28[test_integration_request.py]
    N29[__init__.py]
    N30[ldap_group_mapping.py]
    N31[__init__.py]
    N32[ldap_settings.js]
    N33[ldap_settings.py]
    N34[test_ldap_settings.py]
    N35[__init__.py]
    N36[oauth_authorization_code.js]
    N37[oauth_authorization_code.py]
    N38[test_oauth_authorization_code.py]
    N39[__init__.py]
    N40[oauth_bearer_token.js]
    N41[oauth_bearer_token.py]
    N42[__init__.py]
    N43[clear_old_tokens.py]
    N44[test_oauth_bearer_token.py]
    N45[__init__.py]
    N46[oauth_client.js]
    N47[oauth_client.py]
    N48[__init__.py]
    N49[set_default_allowed_role_in_oauth_client.py]
    N50[test_oauth_client.py]
    N51[__init__.py]
    N52[oauth_client_role.py]
    N53[__init__.py]
    N54[oauth_provider_settings.js]
    N55[oauth_provider_settings.py]
    N56[__init__.py]
    N57[oauth_scope.py]
    N58[__init__.py]
    N59[oauth_settings.js]
    N60[oauth_settings.py]
    N61[test_oauth_settings.py]
    N62[__init__.py]
    N63[push_notification_settings.js]
    N64[push_notification_settings.py]
    N65[test_push_notification_settings.py]
    N66[__init__.py]
    N67[query_parameters.py]
    N68[__init__.py]
    N69[slack_webhook_url.js]
    N70[slack_webhook_url.py]
    N71[test_slack_webhook_url.py]
    N72[__init__.py]
    N73[social_login_key.js]
    N74[social_login_key.py]
    N75[test_social_login_key.py]
    N76[__init__.py]
    N77[social_login_keys.py]
    N78[__init__.py]
    N79[test_token_cache.py]
    N80[token_cache.js]
    N81[token_cache.py]
    N82[__init__.py]
    N83[test_webhook.py]
    N84[webhook.js]
    N85[webhook.py]
    N86[__init__.py]
    N87[webhook_data.py]
    N88[__init__.py]
    N89[webhook_header.py]
    N90[__init__.py]
    N91[test_webhook_request_log.py]
    N92[webhook_request_log.js]
    N93[webhook_request_log.py]
    N94[webhook_request_log_list.js]
    N95[__init__.py]
    N96[frappecloud.py]
    N97[frappecloud_billing.py]
    N98[google_oauth.py]
    N99[oauth2.py]
    N100[oauth2_logins.py]
    N101[utils.py]