graph TD
    N0[__init__.py]
    N1[__init__.py]
    N2[__init__.py]
    N3[customer.js]
    N4[customer.py]
    N5[customer_dashboard.py]
    N6[customer_list.js]
    N7[test_customer.py]
    N8[__init__.py]
    N9[customer_credit_limit.py]
    N10[__init__.py]
    N11[delivery_schedule_item.js]
    N12[delivery_schedule_item.py]
    N13[test_delivery_schedule_item.py]
    N14[__init__.py]
    N15[industry_type.js]
    N16[industry_type.py]
    N17[test_industry_type.py]
    N18[__init__.py]
    N19[installation_note.js]
    N20[installation_note.py]
    N21[test_installation_note.py]
    N22[__init__.py]
    N23[installation_note_item.py]
    N24[__init__.py]
    N25[party_specific_item.js]
    N26[party_specific_item.py]
    N27[test_party_specific_item.py]
    N28[__init__.py]
    N29[product_bundle.js]
    N30[product_bundle.py]
    N31[test_product_bundle.py]
    N32[__init__.py]
    N33[product_bundle_item.py]
    N34[__init__.py]
    N35[quotation.js]
    N36[quotation.py]
    N37[quotation_dashboard.py]
    N38[quotation_list.js]
    N39[test_quotation.py]
    N40[__init__.py]
    N41[quotation_item.py]
    N42[__init__.py]
    N43[sales_order.js]
    N44[sales_order.py]
    N45[sales_order_calendar.js]
    N46[sales_order_dashboard.py]
    N47[sales_order_list.js]
    N48[test_sales_order.py]
    N49[__init__.py]
    N50[sales_order_item.py]
    N51[__init__.py]
    N52[sales_partner_type.js]
    N53[sales_partner_type.py]
    N54[test_sales_partner_type.py]
    N55[__init__.py]
    N56[sales_team.py]
    N57[__init__.py]
    N58[selling_settings.js]
    N59[selling_settings.py]
    N60[test_selling_settings.py]
    N61[__init__.py]
    N62[sms_center.js]
    N63[sms_center.py]
    N64[__init__.py]
    N65[supplier_number_at_customer.py]
    N66[__init__.py]
    N67[__init__.py]
    N68[point_of_sale.js]
    N69[point_of_sale.py]
    N70[pos_controller.js]
    N71[pos_item_cart.js]
    N72[pos_item_details.js]
    N73[pos_item_selector.js]
    N74[pos_number_pad.js]
    N75[pos_past_order_list.js]
    N76[pos_past_order_summary.js]
    N77[pos_payment.js]
    N78[__init__.py]
    N79[sales_funnel.js]
    N80[sales_funnel.py]
    N81[__init__.py]
    N82[__init__.py]
    N83[__init__.py]
    N84[__init__.py]
    N85[__init__.py]
    N86[__init__.py]
    N87[__init__.py]
    N88[__init__.py]
    N89[address_and_contacts.js]
    N90[address_and_contacts.py]
    N91[__init__.py]
    N92[available_stock_for_packing_items.js]
    N93[available_stock_for_packing_items.py]
    N94[__init__.py]
    N95[customer_acquisition_and_loyalty.js]
    N96[customer_acquisition_and_loyalty.py]
    N97[__init__.py]
    N98[customer_credit_balance.js]
    N99[customer_credit_balance.py]
    N100[__init__.py]
    N101[customer_wise_item_price.js]
    N102[customer_wise_item_price.py]
    N103[__init__.py]
    N104[__init__.py]
    N105[inactive_customers.js]
    N106[inactive_customers.py]
    N107[__init__.py]
    N108[item_wise_sales_history.js]
    N109[item_wise_sales_history.py]
    N110[__init__.py]
    N111[lost_quotations.js]
    N112[lost_quotations.py]
    N113[__init__.py]
    N114[payment_terms_status_for_sales_order.js]
    N115[payment_terms_status_for_sales_order.py]
    N116[test_payment_terms_status_for_sales_order.py]
    N117[__init__.py]
    N118[pending_so_items_for_purchase_request.js]
    N119[pending_so_items_for_purchase_request.py]
    N120[test_pending_so_items_for_purchase_request.py]
    N121[__init__.py]
    N122[quotation_trends.js]
    N123[quotation_trends.py]
    N124[__init__.py]
    N125[sales_analytics.js]
    N126[sales_analytics.py]
    N127[test_analytics.py]
    N128[__init__.py]
    N129[sales_order_analysis.js]
    N130[sales_order_analysis.py]
    N131[test_sales_order_analysis.py]
    N132[__init__.py]
    N133[sales_order_trends.js]
    N134[sales_order_trends.py]
    N135[__init__.py]
    N136[sales_partner_commission_summary.js]
    N137[sales_partner_commission_summary.py]
    N138[__init__.py]
    N139[item_group_wise_sales_target_variance.py]
    N140[sales_partner_target_variance_based_on_item_group.js]
    N141[sales_partner_target_variance_based_on_item_group.py]
    N142[test_sales_partner_target_variance_based_on_item_group.py]
    N143[__init__.py]
    N144[sales_partner_transaction_summary.js]
    N145[sales_partner_transaction_summary.py]
    N146[__init__.py]
    N147[sales_person_commission_summary.js]
    N148[sales_person_commission_summary.py]
    N149[__init__.py]
    N150[sales_person_target_variance_based_on_item_group.js]
    N151[sales_person_target_variance_based_on_item_group.py]
    N152[test_sales_person_target_variance_based_on_item_group.py]
    N153[__init__.py]
    N154[sales_person_wise_transaction_summary.js]
    N155[sales_person_wise_transaction_summary.py]
    N156[__init__.py]
    N157[territory_target_variance_based_on_item_group.js]
    N158[territory_target_variance_based_on_item_group.py]
    N159[__init__.py]
    N160[territory_wise_sales.js]
    N161[territory_wise_sales.py]