graph TD
    N0[__init__.py]
    N1[default_success_action.py]
    N2[demo.py]
    N3[__init__.py]
    N4[__init__.py]
    N5[authorization_control.py]
    N6[__init__.py]
    N7[authorization_rule.js]
    N8[authorization_rule.py]
    N9[test_authorization_rule.py]
    N10[__init__.py]
    N11[branch.js]
    N12[branch.py]
    N13[test_branch.py]
    N14[__init__.py]
    N15[brand.js]
    N16[brand.py]
    N17[test_brand.py]
    N18[__init__.py]
    N19[company.js]
    N20[company.py]
    N21[company_dashboard.py]
    N22[company_list.js]
    N23[company_tree.js]
    N24[__init__.py]
    N25[test_company.py]
    N26[__init__.py]
    N27[currency_exchange.js]
    N28[currency_exchange.py]
    N29[test_currency_exchange.py]
    N30[__init__.py]
    N31[customer_group.js]
    N32[customer_group.py]
    N33[customer_group_tree.js]
    N34[test_customer_group.py]
    N35[__init__.py]
    N36[department.js]
    N37[department.py]
    N38[department_tree.js]
    N39[test_department.py]
    N40[__init__.py]
    N41[designation.js]
    N42[designation.py]
    N43[test_designation.py]
    N44[__init__.py]
    N45[driver.js]
    N46[driver.py]
    N47[test_driver.py]
    N48[__init__.py]
    N49[driving_license_category.py]
    N50[__init__.py]
    N51[email_digest.js]
    N52[email_digest.py]
    N53[quotes.py]
    N54[test_email_digest.py]
    N55[__init__.py]
    N56[email_digest_recipient.py]
    N57[__init__.py]
    N58[employee.js]
    N59[employee.py]
    N60[employee_list.js]
    N61[employee_tree.js]
    N62[test_employee.py]
    N63[__init__.py]
    N64[employee_education.py]
    N65[__init__.py]
    N66[employee_external_work_history.py]
    N67[__init__.py]
    N68[employee_group.js]
    N69[employee_group.py]
    N70[test_employee_group.py]
    N71[__init__.py]
    N72[employee_group_table.py]
    N73[__init__.py]
    N74[employee_internal_work_history.py]
    N75[__init__.py]
    N76[global_defaults.js]
    N77[global_defaults.py]
    N78[test_global_defaults.py]
    N79[__init__.py]
    N80[holiday.py]
    N81[__init__.py]
    N82[holiday_list.js]
    N83[holiday_list.py]
    N84[holiday_list_calendar.js]
    N85[holiday_list_dashboard.py]
    N86[test_holiday_list.py]
    N87[__init__.py]
    N88[incoterm.js]
    N89[incoterm.py]
    N90[test_incoterm.py]
    N91[__init__.py]
    N92[item_group.js]
    N93[item_group.py]
    N94[item_group_tree.js]
    N95[test_item_group.py]
    N96[__init__.py]
    N97[party_type.js]
    N98[party_type.py]
    N99[test_party_type.py]
    N100[__init__.py]
    N101[quotation_lost_reason.js]
    N102[quotation_lost_reason.py]
    N103[test_quotation_lost_reason.py]
    N104[__init__.py]
    N105[quotation_lost_reason_detail.py]
    N106[__init__.py]
    N107[sales_partner.js]
    N108[sales_partner.py]
    N109[test_sales_partner.py]
    N110[__init__.py]
    N111[sales_person.js]
    N112[sales_person.py]
    N113[sales_person_dashboard.py]
    N114[sales_person_tree.js]
    N115[__init__.py]
    N116[supplier_group.js]
    N117[supplier_group.py]
    N118[supplier_group_tree.js]
    N119[test_supplier_group.py]
    N120[__init__.py]
    N121[target_detail.py]
    N122[__init__.py]
    N123[terms_and_conditions.js]
    N124[terms_and_conditions.py]
    N125[test_terms_and_conditions.py]
    N126[__init__.py]
    N127[territory.js]
    N128[territory.py]
    N129[territory_tree.js]
    N130[test_territory.py]
    N131[__init__.py]
    N132[test_transaction_deletion_record.py]
    N133[transaction_deletion_record.js]
    N134[transaction_deletion_record.py]
    N135[transaction_deletion_record_list.js]
    N136[__init__.py]
    N137[transaction_deletion_record_item.py]
    N138[__init__.py]
    N139[transaction_deletion_record_to_delete.py]
    N140[__init__.py]
    N141[test_uom.py]
    N142[uom.js]
    N143[uom.py]
    N144[__init__.py]
    N145[test_uom_conversion_factor.py]
    N146[uom_conversion_factor.js]
    N147[uom_conversion_factor.py]
    N148[__init__.py]
    N149[test_vehicle.py]
    N150[vehicle.js]
    N151[vehicle.py]
    N152[vehicle_dashboard.py]
    N153[__init__.py]
    N154[website_item_group.py]
    N155[install.py]
    N156[__init__.py]
    N157[__init__.py]
    N158[__init__.py]
    N159[dashboard_charts.py]
    N160[__init__.py]
    N161[company_setup.py]
    N162[defaults_setup.py]
    N163[install_fixtures.py]
    N164[taxes_setup.py]
    N165[setup_wizard.py]
    N166[utils.py]