graph TD
    N0[__init__.py]
    N1[address.py]
    N2[__init__.py]
    N3[__init__.py]
    N4[account_balance_timeline.js]
    N5[account_balance_timeline.py]
    N6[deferred_revenue.py]
    N7[__init__.py]
    N8[__init__.py]
    N9[account.js]
    N10[account.py]
    N11[account_tree.js]
    N12[__init__.py]
    N13[chart_of_accounts.py]
    N14[__init__.py]
    N15[standard_chart_of_accounts.py]
    N16[standard_chart_of_accounts_with_account_number.py]
    N17[syscohada_chart_of_accounts.py]
    N18[test_account.py]
    N19[__init__.py]
    N20[account_category.js]
    N21[account_category.py]
    N22[test_account_category.py]
    N23[__init__.py]
    N24[account_closing_balance.js]
    N25[account_closing_balance.py]
    N26[test_account_closing_balance.py]
    N27[__init__.py]
    N28[accounting_dimension.js]
    N29[accounting_dimension.py]
    N30[test_accounting_dimension.py]
    N31[__init__.py]
    N32[accounting_dimension_detail.py]
    N33[__init__.py]
    N34[accounting_dimension_filter.js]
    N35[accounting_dimension_filter.py]
    N36[test_accounting_dimension_filter.py]
    N37[__init__.py]
    N38[accounting_period.js]
    N39[accounting_period.py]
    N40[test_accounting_period.py]
    N41[__init__.py]
    N42[accounts_settings.js]
    N43[accounts_settings.py]
    N44[united_states.js]
    N45[test_accounts_settings.py]
    N46[__init__.py]
    N47[advance_payment_ledger_entry.js]
    N48[advance_payment_ledger_entry.py]
    N49[test_advance_payment_ledger_entry.py]
    N50[__init__.py]
    N51[advance_taxes_and_charges.py]
    N52[__init__.py]
    N53[allowed_dimension.py]
    N54[__init__.py]
    N55[allowed_to_transact_with.py]
    N56[__init__.py]
    N57[applicable_on_account.py]
    N58[__init__.py]
    N59[bank.js]
    N60[bank.py]
    N61[bank_dashboard.py]
    N62[test_bank.py]
    N63[__init__.py]
    N64[bank_account.js]
    N65[bank_account.py]
    N66[test_bank_account.py]
    N67[__init__.py]
    N68[bank_account_subtype.js]
    N69[bank_account_subtype.py]
    N70[test_bank_account_subtype.py]
    N71[__init__.py]
    N72[bank_account_type.js]
    N73[bank_account_type.py]
    N74[test_bank_account_type.py]
    N75[__init__.py]
    N76[bank_clearance.js]
    N77[bank_clearance.py]
    N78[test_bank_clearance.py]
    N79[__init__.py]
    N80[bank_clearance_detail.py]
    N81[__init__.py]
    N82[bank_guarantee.js]
    N83[bank_guarantee.py]
    N84[test_bank_guarantee.py]
    N85[__init__.py]
    N86[bank_reconciliation_tool.js]
    N87[bank_reconciliation_tool.py]
    N88[test_bank_reconciliation_tool.py]
    N89[__init__.py]
    N90[bank_statement_import.js]
    N91[bank_statement_import.py]
    N92[bank_statement_import_list.js]
    N93[test_bank_statement_import.py]
    N94[__init__.py]
    N95[auto_match_party.py]
    N96[bank_transaction.js]
    N97[bank_transaction.py]
    N98[bank_transaction_list.js]
    N99[bank_transaction_upload.py]
    N100[test_auto_match_party.py]
    N101[test_bank_transaction.py]
    N102[test_bank_transaction_fees.py]
    N103[__init__.py]
    N104[bank_transaction_mapping.py]
    N105[__init__.py]
    N106[bank_transaction_payments.py]
    N107[__init__.py]
    N108[bisect_accounting_statements.js]
    N109[bisect_accounting_statements.py]
    N110[test_bisect_accounting_statements.py]
    N111[__init__.py]
    N112[bisect_nodes.js]
    N113[bisect_nodes.py]
    N114[test_bisect_nodes.py]
    N115[__init__.py]
    N116[budget.js]
    N117[budget.py]
    N118[test_budget.py]
    N119[__init__.py]
    N120[budget_account.py]
    N121[__init__.py]
    N122[budget_distribution.py]
    N123[__init__.py]
    N124[campaign_item.py]
    N125[__init__.py]
    N126[cashier_closing.js]
    N127[cashier_closing.py]
    N128[test_cashier_closing.py]
    N129[__init__.py]
    N130[cashier_closing_payments.py]
    N131[__init__.py]
    N132[chart_of_accounts_importer.js]
    N133[chart_of_accounts_importer.py]
    N134[test_chart_of_accounts_importer.py]
    N135[__init__.py]
    N136[cheque_print_template.js]
    N137[cheque_print_template.py]
    N138[test_cheque_print_template.py]
    N139[__init__.py]
    N140[closed_document.py]
    N141[__init__.py]
    N142[cost_center.js]
    N143[cost_center.py]
    N144[cost_center_dashboard.py]
    N145[cost_center_tree.js]
    N146[test_cost_center.py]
    N147[__init__.py]
    N148[cost_center_allocation.js]
    N149[cost_center_allocation.py]
    N150[test_cost_center_allocation.py]
    N151[__init__.py]
    N152[cost_center_allocation_percentage.py]
    N153[__init__.py]
    N154[coupon_code.js]
    N155[coupon_code.py]
    N156[test_coupon_code.py]
    N157[__init__.py]
    N158[currency_exchange_settings.js]
    N159[currency_exchange_settings.py]
    N160[test_currency_exchange_settings.py]
    N161[__init__.py]
    N162[currency_exchange_settings_details.py]
    N163[__init__.py]
    N164[currency_exchange_settings_result.py]
    N165[__init__.py]
    N166[customer_group_item.py]
    N167[__init__.py]
    N168[customer_item.py]
    N169[__init__.py]
    N170[discounted_invoice.py]
    N171[__init__.py]
    N172[dunning.js]
    N173[dunning.py]
    N174[dunning_list.js]
    N175[test_dunning.py]
    N176[__init__.py]
    N177[dunning_letter_text.py]
    N178[__init__.py]
    N179[dunning_type.js]
    N180[dunning_type.py]
    N181[test_dunning_type.py]
    N182[__init__.py]
    N183[exchange_rate_revaluation.js]
    N184[exchange_rate_revaluation.py]
    N185[exchange_rate_revaluation_dashboard.py]
    N186[test_exchange_rate_revaluation.py]
    N187[__init__.py]
    N188[exchange_rate_revaluation_account.py]
    N189[__init__.py]
    N190[finance_book.js]
    N191[finance_book.py]
    N192[finance_book_dashboard.py]
    N193[test_finance_book.py]
    N194[__init__.py]
    N195[financial_report_row.py]
    N196[__init__.py]
    N197[financial_report_engine.py]
    N198[financial_report_template.js]
    N199[financial_report_template.py]
    N200[financial_report_validation.py]
    N201[test_financial_report_engine.py]
    N202[test_financial_report_template.py]
    N203[__init__.py]
    N204[fiscal_year.js]
    N205[fiscal_year.py]
    N206[fiscal_year_dashboard.py]
    N207[test_fiscal_year.py]
    N208[__init__.py]
    N209[fiscal_year_company.py]
    N210[__init__.py]
    N211[gl_entry.js]
    N212[gl_entry.py]
    N213[test_gl_entry.py]
    N214[__init__.py]
    N215[invoice_discounting.js]
    N216[invoice_discounting.py]
    N217[invoice_discounting_dashboard.py]
    N218[invoice_discounting_list.js]
    N219[test_invoice_discounting.py]
    N220[__init__.py]
    N221[item_tax_template.js]
    N222[item_tax_template.py]
    N223[item_tax_template_dashboard.py]
    N224[test_item_tax_template.py]
    N225[__init__.py]
    N226[item_tax_template_detail.py]
    N227[__init__.py]
    N228[item_wise_tax_detail.py]
    N229[__init__.py]
    N230[journal_entry.js]
    N231[journal_entry.py]
    N232[journal_entry_list.js]
    N233[test_journal_entry.py]
    N234[__init__.py]
    N235[journal_entry_account.py]
    N236[__init__.py]
    N237[journal_entry_template.js]
    N238[journal_entry_template.py]
    N239[test_journal_entry_template.py]
    N240[__init__.py]
    N241[journal_entry_template_account.py]
    N242[__init__.py]
    N243[ledger_health.js]
    N244[ledger_health.py]
    N245[test_ledger_health.py]
    N246[__init__.py]
    N247[ledger_health_monitor.js]
    N248[ledger_health_monitor.py]
    N249[test_ledger_health_monitor.py]
    N250[__init__.py]
    N251[ledger_health_monitor_company.py]
    N252[__init__.py]
    N253[ledger_merge.js]
    N254[ledger_merge.py]
    N255[test_ledger_merge.py]
    N256[__init__.py]
    N257[ledger_merge_accounts.py]
    N258[__init__.py]
    N259[loyalty_point_entry.js]
    N260[loyalty_point_entry.py]
    N261[test_loyalty_point_entry.py]
    N262[__init__.py]
    N263[loyalty_point_entry_redemption.py]
    N264[__init__.py]
    N265[loyalty_program.js]
    N266[loyalty_program.py]
    N267[loyalty_program_dashboard.py]
    N268[test_loyalty_program.py]
    N269[__init__.py]
    N270[loyalty_program_collection.py]
    N271[__init__.py]
    N272[mode_of_payment.js]
    N273[mode_of_payment.py]
    N274[test_mode_of_payment.py]
    N275[__init__.py]
    N276[mode_of_payment_account.py]
    N277[__init__.py]
    N278[monthly_distribution.js]
    N279[monthly_distribution.py]
    N280[monthly_distribution_dashboard.py]
    N281[test_monthly_distribution.py]
    N282[__init__.py]
    N283[monthly_distribution_percentage.py]
    N284[__init__.py]
    N285[opening_invoice_creation_tool.js]
    N286[opening_invoice_creation_tool.py]
    N287[test_opening_invoice_creation_tool.py]
    N288[__init__.py]
    N289[opening_invoice_creation_tool_item.py]
    N290[__init__.py]
    N291[overdue_payment.py]
    N292[__init__.py]
    N293[party_account.py]
    N294[__init__.py]
    N295[party_link.js]
    N296[party_link.py]
    N297[test_party_link.py]
    N298[__init__.py]
    N299[payment_entry.js]
    N300[payment_entry.py]
    N301[payment_entry_list.js]
    N302[test_payment_entry.py]
    N303[__init__.py]
    N304[payment_entry_deduction.py]
    N305[__init__.py]
    N306[payment_entry_reference.py]
    N307[__init__.py]
    N308[payment_gateway_account.js]
    N309[payment_gateway_account.py]
    N310[payment_gateway_account_dashboard.py]
    N311[test_payment_gateway_account.py]
    N312[__init__.py]
    N313[payment_ledger_entry.js]
    N314[payment_ledger_entry.py]
    N315[test_payment_ledger_entry.py]
    N316[__init__.py]
    N317[payment_order.js]
    N318[payment_order.py]
    N319[payment_order_dashboard.py]
    N320[test_payment_order.py]
    N321[__init__.py]
    N322[payment_order_reference.py]
    N323[__init__.py]
    N324[payment_reconciliation.js]
    N325[payment_reconciliation.py]
    N326[test_payment_reconciliation.py]
    N327[__init__.py]
    N328[payment_reconciliation_allocation.py]
    N329[__init__.py]
    N330[payment_reconciliation_invoice.py]
    N331[__init__.py]
    N332[payment_reconciliation_payment.py]
    N333[__init__.py]
    N334[payment_request.js]
    N335[payment_request.py]
    N336[payment_request_dashboard.py]
    N337[payment_request_list.js]
    N338[test_payment_request.py]
    N339[__init__.py]
    N340[payment_schedule.py]
    N341[__init__.py]
    N342[payment_term.js]
    N343[payment_term.py]
    N344[payment_term_dashboard.py]
    N345[test_payment_term.py]
    N346[__init__.py]
    N347[payment_terms_template.js]
    N348[payment_terms_template.py]
    N349[payment_terms_template_dashboard.py]
    N350[test_payment_terms_template.py]
    N351[__init__.py]
    N352[payment_terms_template_detail.py]
    N353[__init__.py]
    N354[pegged_currencies.js]
    N355[pegged_currencies.py]
    N356[test_pegged_currencies.py]
    N357[__init__.py]
    N358[pegged_currency_details.py]
    N359[__init__.py]
    N360[period_closing_voucher.js]
    N361[period_closing_voucher.py]
    N362[test_period_closing_voucher.py]
    N363[__init__.py]
    N364[pos_closing_entry.js]
    N365[pos_closing_entry.py]
    N366[pos_closing_entry_list.js]
    N367[test_pos_closing_entry.py]
    N368[__init__.py]
    N369[pos_closing_entry_detail.py]
    N370[__init__.py]
    N371[pos_closing_entry_taxes.py]
    N372[__init__.py]
    N373[pos_customer_group.py]
    N374[__init__.py]
    N375[pos_field.py]
    N376[__init__.py]
    N377[pos_invoice.js]
    N378[pos_invoice.py]
    N379[pos_invoice_list.js]
    N380[test_pos_invoice.py]
    N381[__init__.py]
    N382[pos_invoice_item.py]
    N383[__init__.py]
    N384[pos_invoice_merge_log.js]
    N385[pos_invoice_merge_log.py]
    N386[test_pos_invoice_merge_log.py]
    N387[__init__.py]
    N388[pos_invoice_reference.py]
    N389[__init__.py]
    N390[pos_item_group.py]
    N391[__init__.py]
    N392[pos_opening_entry.js]
    N393[pos_opening_entry.py]
    N394[pos_opening_entry_list.js]
    N395[test_pos_opening_entry.py]
    N396[__init__.py]
    N397[pos_opening_entry_detail.py]
    N398[__init__.py]
    N399[pos_payment_method.py]
    N400[__init__.py]
    N401[pos_profile.js]
    N402[pos_profile.py]
    N403[test_pos_profile.py]
    N404[__init__.py]
    N405[pos_profile_user.js]
    N406[pos_profile_user.py]
    N407[test_pos_profile_user.py]
    N408[__init__.py]
    N409[pos_search_fields.py]
    N410[__init__.py]
    N411[pos_settings.js]
    N412[pos_settings.py]
    N413[test_pos_settings.py]
    N414[__init__.py]
    N415[pricing_rule.js]
    N416[pricing_rule.py]
    N417[test_pricing_rule.py]
    N418[utils.py]
    N419[__init__.py]
    N420[pricing_rule_brand.py]
    N421[__init__.py]
    N422[pricing_rule_detail.py]
    N423[__init__.py]
    N424[pricing_rule_item_code.py]
    N425[__init__.py]
    N426[pricing_rule_item_group.py]
    N427[__init__.py]
    N428[process_deferred_accounting.js]
    N429[process_deferred_accounting.py]
    N430[test_process_deferred_accounting.py]
    N431[__init__.py]
    N432[process_payment_reconciliation.js]
    N433[process_payment_reconciliation.py]
    N434[process_payment_reconciliation_dashboard.py]
    N435[process_payment_reconciliation_list.js]
    N436[test_process_payment_reconciliation.py]
    N437[__init__.py]
    N438[process_payment_reconciliation_log.js]
    N439[process_payment_reconciliation_log.py]
    N440[process_payment_reconciliation_log_list.js]
    N441[test_process_payment_reconciliation_log.py]
    N442[__init__.py]
    N443[process_payment_reconciliation_log_allocations.py]
    N444[__init__.py]
    N445[process_period_closing_voucher.js]
    N446[process_period_closing_voucher.py]
    N447[test_process_period_closing_voucher.py]
    N448[__init__.py]
    N449[process_period_closing_voucher_detail.py]
    N450[__init__.py]
    N451[process_statement_of_accounts.js]
    N452[process_statement_of_accounts.py]
    N453[test_process_statement_of_accounts.py]
    N454[__init__.py]
    N455[process_statement_of_accounts_cc.py]
    N456[__init__.py]
    N457[process_statement_of_accounts_customer.py]
    N458[__init__.py]
    N459[process_subscription.js]
    N460[process_subscription.py]
    N461[test_process_subscription.py]
    N462[__init__.py]
    N463[promotional_scheme.js]
    N464[promotional_scheme.py]
    N465[promotional_scheme_dashboard.py]
    N466[test_promotional_scheme.py]
    N467[__init__.py]
    N468[promotional_scheme_price_discount.py]
    N469[__init__.py]
    N470[promotional_scheme_product_discount.py]
    N471[__init__.py]
    N472[psoa_cost_center.py]
    N473[__init__.py]
    N474[psoa_project.py]
    N475[__init__.py]
    N476[purchase_invoice.js]
    N477[purchase_invoice.py]
    N478[purchase_invoice_dashboard.py]
    N479[purchase_invoice_list.js]
    N480[test_purchase_invoice.py]
    N481[__init__.py]
    N482[purchase_invoice_advance.py]
    N483[__init__.py]
    N484[purchase_invoice_item.py]
    N485[__init__.py]
    N486[purchase_taxes_and_charges.py]
    N487[__init__.py]
    N488[purchase_taxes_and_charges_template.js]
    N489[purchase_taxes_and_charges_template.py]
    N490[purchase_taxes_and_charges_template_dashboard.py]
    N491[test_purchase_taxes_and_charges_template.py]
    N492[__init__.py]
    N493[repost_accounting_ledger.js]
    N494[repost_accounting_ledger.py]
    N495[test_repost_accounting_ledger.py]
    N496[__init__.py]
    N497[repost_accounting_ledger_items.py]
    N498[__init__.py]
    N499[repost_accounting_ledger_settings.js]
    N500[repost_accounting_ledger_settings.py]
    N501[test_repost_accounting_ledger_settings.py]
    N502[__init__.py]
    N503[repost_allowed_types.py]
    N504[__init__.py]
    N505[repost_payment_ledger.js]
    N506[repost_payment_ledger.py]
    N507[repost_payment_ledger_list.js]
    N508[test_repost_payment_ledger.py]
    N509[__init__.py]
    N510[repost_payment_ledger_items.py]
    N511[__init__.py]
    N512[italy.js]
    N513[sales_invoice.js]
    N514[sales_invoice.py]
    N515[sales_invoice_dashboard.py]
    N516[sales_invoice_list.js]
    N517[test_sales_invoice.py]
    N518[__init__.py]
    N519[sales_invoice_advance.py]
    N520[__init__.py]
    N521[sales_invoice_item.py]
    N522[__init__.py]
    N523[sales_invoice_payment.py]
    N524[__init__.py]
    N525[sales_invoice_reference.py]
    N526[__init__.py]
    N527[sales_invoice_timesheet.py]
    N528[__init__.py]
    N529[sales_partner_item.py]
    N530[__init__.py]
    N531[sales_taxes_and_charges.py]
    N532[__init__.py]
    N533[sales_taxes_and_charges_template.js]
    N534[sales_taxes_and_charges_template.py]
    N535[sales_taxes_and_charges_template_dashboard.py]
    N536[test_sales_taxes_and_charges_template.py]
    N537[__init__.py]
    N538[share_balance.py]
    N539[__init__.py]
    N540[share_transfer.js]
    N541[share_transfer.py]
    N542[test_share_transfer.py]
    N543[__init__.py]
    N544[share_type.js]
    N545[share_type.py]
    N546[share_type_dashboard.py]
    N547[test_share_type.py]
    N548[__init__.py]
    N549[shareholder.js]
    N550[shareholder.py]
    N551[shareholder_dashboard.py]
    N552[test_shareholder.py]
    N553[__init__.py]
    N554[shipping_rule.js]
    N555[shipping_rule.py]
    N556[shipping_rule_dashboard.py]
    N557[test_shipping_rule.py]
    N558[__init__.py]
    N559[shipping_rule_condition.py]
    N560[__init__.py]
    N561[shipping_rule_country.py]
    N562[__init__.py]
    N563[south_africa_vat_account.py]
    N564[__init__.py]
    N565[subscription.js]
    N566[subscription.py]
    N567[subscription_list.js]
    N568[test_subscription.py]
    N569[__init__.py]
    N570[subscription_invoice.js]
    N571[subscription_invoice.py]
    N572[test_subscription_invoice.py]
    N573[__init__.py]
    N574[subscription_plan.js]
    N575[subscription_plan.py]
    N576[subscription_plan_dashboard.py]
    N577[test_subscription_plan.py]
    N578[__init__.py]
    N579[subscription_plan_detail.py]
    N580[__init__.py]
    N581[subscription_settings.js]
    N582[subscription_settings.py]
    N583[test_subscription_settings.py]
    N584[__init__.py]
    N585[supplier_group_item.py]
    N586[__init__.py]
    N587[supplier_item.py]
    N588[__init__.py]
    N589[tax_category.js]
    N590[tax_category.py]
    N591[tax_category_dashboard.py]
    N592[test_tax_category.py]
    N593[__init__.py]
    N594[tax_rule.js]
    N595[tax_rule.py]
    N596[test_tax_rule.py]
    N597[__init__.py]
    N598[tax_withholding_account.py]
    N599[__init__.py]
    N600[tax_withholding_category.js]
    N601[tax_withholding_category.py]
    N602[tax_withholding_category_dashboard.py]
    N603[test_tax_withholding_category.py]
    N604[__init__.py]
    N605[tax_withholding_entry.py]
    N606[test_tax_withholding_entry.py]
    N607[__init__.py]
    N608[tax_withholding_group.js]
    N609[tax_withholding_group.py]
    N610[test_tax_withholding_group.py]
    N611[__init__.py]
    N612[tax_withholding_rate.py]
    N613[__init__.py]
    N614[territory_item.py]
    N615[__init__.py]
    N616[transaction_deletion_record_details.py]
    N617[__init__.py]
    N618[test_unreconcile_payment.py]
    N619[unreconcile_payment.js]
    N620[unreconcile_payment.py]
    N621[__init__.py]
    N622[unreconcile_payment_entries.py]
    N623[__init__.py]
    N624[__init__.py]
    N625[__init__.py]
    N626[__init__.py]
    N627[__init__.py]
    N628[__init__.py]
    N629[__init__.py]
    N630[general_ledger.py]
    N631[__init__.py]
    N632[__init__.py]
    N633[notification_for_new_fiscal_year.py]
    N634[__init__.py]
    N635[party.py]
    N636[__init__.py]
    N637[__init__.py]
    N638[__init__.py]
    N639[__init__.py]
    N640[__init__.py]
    N641[__init__.py]
    N642[__init__.py]
    N643[__init__.py]
    N644[__init__.py]
    N645[__init__.py]
    N646[__init__.py]
    N647[__init__.py]
    N648[__init__.py]
    N649[__init__.py]
    N650[__init__.py]
    N651[__init__.py]
    N652[__init__.py]
    N653[__init__.py]
    N654[__init__.py]
    N655[__init__.py]
    N656[__init__.py]
    N657[__init__.py]
    N658[account_balance.js]
    N659[account_balance.py]
    N660[test_account_balance.py]
    N661[__init__.py]
    N662[accounts_payable.js]
    N663[accounts_payable.py]
    N664[test_accounts_payable.py]
    N665[__init__.py]
    N666[accounts_payable_summary.js]
    N667[accounts_payable_summary.py]
    N668[__init__.py]
    N669[accounts_receivable.js]
    N670[accounts_receivable.py]
    N671[test_accounts_receivable.py]
    N672[__init__.py]
    N673[accounts_receivable_summary.js]
    N674[accounts_receivable_summary.py]
    N675[test_accounts_receivable_summary.py]
    N676[__init__.py]
    N677[asset_depreciation_ledger.js]
    N678[asset_depreciation_ledger.py]
    N679[__init__.py]
    N680[asset_depreciations_and_balances.js]
    N681[asset_depreciations_and_balances.py]
    N682[__init__.py]
    N683[balance_sheet.js]
    N684[balance_sheet.py]
    N685[test_balance_sheet.py]
    N686[__init__.py]
    N687[bank_clearance_summary.js]
    N688[bank_clearance_summary.py]
    N689[__init__.py]
    N690[bank_reconciliation_statement.js]
    N691[bank_reconciliation_statement.py]
    N692[test_bank_reconciliation_statement.py]
    N693[__init__.py]
    N694[billed_items_to_be_received.js]
    N695[billed_items_to_be_received.py]
    N696[__init__.py]
    N697[budget_variance_report.js]
    N698[budget_variance_report.py]
    N699[__init__.py]
    N700[calculated_discount_mismatch.js]
    N701[calculated_discount_mismatch.py]
    N702[__init__.py]
    N703[cash_flow.js]
    N704[cash_flow.py]
    N705[__init__.py]
    N706[cheques_and_deposits_incorrectly_cleared.js]
    N707[cheques_and_deposits_incorrectly_cleared.py]
    N708[__init__.py]
    N709[consolidated_financial_statement.js]
    N710[consolidated_financial_statement.py]
    N711[__init__.py]
    N712[consolidated_trial_balance.js]
    N713[consolidated_trial_balance.py]
    N714[test_consolidated_trial_balance.py]
    N715[__init__.py]
    N716[custom_financial_statement.js]
    N717[custom_financial_statement.py]
    N718[__init__.py]
    N719[customer_ledger_summary.js]
    N720[customer_ledger_summary.py]
    N721[test_customer_ledger_summary.py]
    N722[__init__.py]
    N723[deferred_revenue_and_expense.js]
    N724[deferred_revenue_and_expense.py]
    N725[test_deferred_revenue_and_expense.py]
    N726[__init__.py]
    N727[delivered_items_to_be_billed.js]
    N728[delivered_items_to_be_billed.py]
    N729[__init__.py]
    N730[dimension_wise_accounts_balance_report.js]
    N731[dimension_wise_accounts_balance_report.py]
    N732[__init__.py]
    N733[financial_ratios.js]
    N734[financial_ratios.py]
    N735[financial_statements.py]
    N736[__init__.py]
    N737[general_and_payment_ledger_comparison.js]
    N738[general_and_payment_ledger_comparison.py]
    N739[test_general_and_payment_ledger_comparison.py]
    N740[__init__.py]
    N741[general_ledger.js]
    N742[general_ledger.py]
    N743[test_general_ledger.py]
    N744[__init__.py]
    N745[gross_and_net_profit_report.js]
    N746[gross_and_net_profit_report.py]
    N747[__init__.py]
    N748[gross_profit.js]
    N749[gross_profit.py]
    N750[test_gross_profit.py]
    N751[__init__.py]
    N752[inactive_sales_items.js]
    N753[inactive_sales_items.py]
    N754[__init__.py]
    N755[invalid_ledger_entries.js]
    N756[invalid_ledger_entries.py]
    N757[__init__.py]
    N758[item_wise_purchase_register.js]
    N759[item_wise_purchase_register.py]
    N760[test_item_wise_purchase_register.py]
    N761[__init__.py]
    N762[item_wise_sales_register.js]
    N763[item_wise_sales_register.py]
    N764[test_item_wise_sales_register.py]
    N765[non_billed_report.py]
    N766[__init__.py]
    N767[payment_ledger.js]
    N768[payment_ledger.py]
    N769[test_payment_ledger.py]
    N770[__init__.py]
    N771[payment_period_based_on_invoice_date.js]
    N772[payment_period_based_on_invoice_date.py]
    N773[__init__.py]
    N774[pos_register.js]
    N775[pos_register.py]
    N776[__init__.py]
    N777[profit_and_loss_statement.js]
    N778[profit_and_loss_statement.py]
    N779[test_profit_and_loss_statement.py]
    N780[__init__.py]
    N781[profitability_analysis.js]
    N782[profitability_analysis.py]
    N783[__init__.py]
    N784[purchase_invoice_trends.js]
    N785[purchase_invoice_trends.py]
    N786[__init__.py]
    N787[purchase_register.js]
    N788[purchase_register.py]
    N789[test_purchase_register.py]
    N790[__init__.py]
    N791[received_items_to_be_billed.js]
    N792[received_items_to_be_billed.py]
    N793[__init__.py]
    N794[sales_invoice_trends.js]
    N795[sales_invoice_trends.py]
    N796[__init__.py]
    N797[__init__.py]
    N798[sales_payment_summary.js]
    N799[sales_payment_summary.py]
    N800[test_sales_payment_summary.py]
    N801[__init__.py]
    N802[sales_register.js]
    N803[sales_register.py]
    N804[test_sales_register.py]
    N805[__init__.py]
    N806[share_balance.js]
    N807[share_balance.py]
    N808[__init__.py]
    N809[share_ledger.js]
    N810[share_ledger.py]
    N811[__init__.py]
    N812[supplier_ledger_summary.js]
    N813[supplier_ledger_summary.py]
    N814[test_supplier_ledger_summary.py]
    N815[__init__.py]
    N816[tax_withholding_details.js]
    N817[tax_withholding_details.py]
    N818[test_tax_withholding_details.py]
    N819[__init__.py]
    N820[tds_computation_summary.js]
    N821[tds_computation_summary.py]
    N822[__init__.py]
    N823[test_trial_balance.py]
    N824[trial_balance.js]
    N825[trial_balance.py]
    N826[__init__.py]
    N827[trial_balance_for_party.js]
    N828[trial_balance_for_party.py]
    N829[__init__.py]
    N830[utils.py]
    N831[__init__.py]
    N832[voucher_wise_balance.js]
    N833[voucher_wise_balance.py]
    N834[__init__.py]
    N835[accounts_mixin.py]
    N836[test_reports.py]
    N837[test_utils.py]
    N838[test_party.py]
    N839[utils.py]