graph TD
    N0[.postcssrc.js]
    N1[auto-imports.d.ts]
    N2[config.ts]
    N3[meta.ts]
    N4[componentTransformer.ts]
    N5[index.ts]
    N6[utils.ts]
    N7[cache.ts]
    N8[auto-imports.d.ts]
    N9[[token].paths.ts]
    N10[propsgen.ts]
    N11[state.ts]
    N12[dataImport.ts]
    N13[types.ts]
    N14[types.ts]
    N15[utils.ts]
    N16[help.js]
    N17[helpCenter.js]
    N18[index.ts]
    N19[types.ts]
    N20[onboarding.js]
    N21[types.ts]
    N22[types.ts]
    N23[utils.ts]
    N24[index.js]
    N25[icons.js]
    N26[resources.js]
    N27[utils.js]
    N28[index.d.ts]
    N29[index.js]
    N30[session.js]
    N31[index.ts]
    N32[pulse.ts]
    N33[telemetry.test.ts]
    N34[utils.ts]
    N35[index.ts]
    N36[spritePlugin.ts]
    N37[main.js]
    N38[postcss.config.ts]
    N39[index.ts]
    N40[types.ts]
    N41[index.ts]
    N42[types.ts]
    N43[index.ts]
    N44[types.ts]
    N45[index.ts]
    N46[types.ts]
    N47[index.ts]
    N48[types.ts]
    N49[index.ts]
    N50[types.ts]
    N51[calendarUtils.js]
    N52[useCalendarData.js]
    N53[useEventModal.js]
    N54[index.ts]
    N55[axisChartOptions.ts]
    N56[donutChartOptions.ts]
    N57[eChartOptions.ts]
    N58[funnelChartOptions.ts]
    N59[helpers.ts]
    N60[index.ts]
    N61[types.ts]
    N62[index.ts]
    N63[types.ts]
    N64[index.ts]
    N65[types.ts]
    N66[index.ts]
    N67[types.ts]
    N68[index.ts]
    N69[types.ts]
    N70[useDatePicker.ts]
    N71[utils.ts]
    N72[index.ts]
    N73[types.ts]
    N74[index.ts]
    N75[types.ts]
    N76[index.ts]
    N77[types.ts]
    N78[index.ts]
    N79[types.ts]
    N80[index.ts]
    N81[index.ts]
    N82[types.ts]
    N83[utils.js]
    N84[index.ts]
    N85[types.ts]
    N86[index.ts]
    N87[types.ts]
    N88[index.ts]
    N89[types.ts]
    N90[index.ts]
    N91[types.ts]
    N92[index.ts]
    N93[types.ts]
    N94[index.ts]
    N95[types.ts]
    N96[index.ts]
    N97[types.ts]
    N98[index.ts]
    N99[types.ts]
    N100[index.ts]
    N101[types.ts]
    N102[index.ts]
    N103[types.ts]
    N104[index.ts]
    N105[types.ts]
    N106[commands.js]
    N107[index.js]
    N108[code-block.ts]
    N109[color-extension.ts]
    N110[index.ts]
    N111[content-paste-extension.ts]
    N112[copy-styles.ts]
    N113[emoji-extension.ts]
    N114[heading.ts]
    N115[highlight-extension.ts]
    N116[index.ts]
    N117[iframe-extension.ts]
    N118[index.ts]
    N119[utils.ts]
    N120[image-extension.ts]
    N121[index.ts]
    N122[image-group-extension.ts]
    N123[image-viewer-extension.ts]
    N124[index.ts]
    N125[link-extension.ts]
    N126[linkPasteHandler.ts]
    N127[index.ts]
    N128[mention-extension.ts]
    N129[color-utils.ts]
    N130[slash-commands-extension.ts]
    N131[createSuggestionExtension.ts]
    N132[index.ts]
    N133[index.ts]
    N134[tag-extension.ts]
    N135[index.ts]
    N136[toc-node-extension.ts]
    N137[video-extension.ts]
    N138[index.ts]
    N139[types.ts]
    N140[utils.js]
    N141[index.ts]
    N142[types.ts]
    N143[index.ts]
    N144[types.ts]
    N145[index.ts]
    N146[types.ts]
    N147[index.ts]
    N148[types.ts]
    N149[index.ts]
    N150[types.ts]
    N151[index.ts]
    N152[types.ts]
    N153[types.ts]
    N154[TextInput.ts]
    N155[useImageNavigation.ts]
    N156[useTouchHandler.ts]
    N157[useZoomPan.ts]
    N158[docStore.ts]
    N159[idbStore.ts]
    N160[index.ts]
    N161[types.ts]
    N162[useCall.test.ts]
    N163[useCall.ts]
    N164[useDoc.test.ts]
    N165[useDoc.ts]
    N166[useDoctype.test.ts]
    N167[useDoctype.ts]
    N168[useFrappeFetch.ts]
    N169[listStore.ts]
    N170[types.ts]
    N171[useList.test.ts]
    N172[useList.ts]
    N173[useNewDoc.ts]
    N174[utils.ts]
    N175[focus.ts]
    N176[onOutsideClick.ts]
    N177[visibility.ts]
    N178[env.d.ts]
    N179[index.ts]
    N180[handlers.ts]
    N181[node.ts]
    N182[utils.ts]
    N183[documentResource.js]
    N184[index.ts]
    N185[listResource.js]
    N186[local.ts]
    N187[plugin.js]
    N188[realtime.ts]
    N189[resources.js]
    N190[call.js]
    N191[config.ts]
    N192[confirmDialog.js]
    N193[dayjs.ts]
    N194[debounce.ts]
    N195[file-to-base64.ts]
    N196[fileUploadHandler.ts]
    N197[frappeRequest.js]
    N198[markdown.ts]
    N199[pageMeta.ts]
    N200[plugin.js]
    N201[request.js]
    N202[socketio.js]
    N203[tailwind.config.js]
    N204[theme.ts]
    N205[url-validation.ts]
    N206[useFileUpload.ts]
    N207[useId.ts]
    N208[colorPalette.js]
    N209[colors.js]
    N210[figma-variables-to-colors.js]
    N211[index.js]
    N212[plugin.js]
    N213[preset.js]
    N214[update-tailwind-classes.js]
    N215[tailwind.config.js]
    N216[buildConfig.js]
    N217[doctypeInterfaceGenerator.js]
    N218[frappeProxy.js]
    N219[frappeTypes.js]
    N220[generateTypes.js]
    N221[index.js]
    N222[jinjaBootData.js]
    N223[lucideIcons.js]
    N224[utils.js]
    N225[vite.config.ts]
    N226[vitest.config.ts]
    N227[vitest.setup.ts]