graph TD
    N0[__init__.py]
    N1[__init__.py]
    N2[__init__.py]
    N3[appointment.js]
    N4[appointment.py]
    N5[test_appointment.py]
    N6[__init__.py]
    N7[appointment_booking_settings.js]
    N8[appointment_booking_settings.py]
    N9[test_appointment_booking_settings.py]
    N10[__init__.py]
    N11[appointment_booking_slots.py]
    N12[__init__.py]
    N13[availability_of_slots.py]
    N14[__init__.py]
    N15[campaign.js]
    N16[campaign.py]
    N17[test_campaign.py]
    N18[__init__.py]
    N19[campaign_email_schedule.py]
    N20[__init__.py]
    N21[competitor.js]
    N22[competitor.py]
    N23[test_competitor.py]
    N24[__init__.py]
    N25[competitor_detail.py]
    N26[__init__.py]
    N27[contract.js]
    N28[contract.py]
    N29[contract_list.js]
    N30[test_contract.py]
    N31[__init__.py]
    N32[contract_fulfilment_checklist.js]
    N33[contract_fulfilment_checklist.py]
    N34[test_contract_fulfilment_checklist.py]
    N35[__init__.py]
    N36[contract_template.js]
    N37[contract_template.py]
    N38[test_contract_template.py]
    N39[__init__.py]
    N40[contract_template_fulfilment_terms.py]
    N41[__init__.py]
    N42[crm_note.py]
    N43[__init__.py]
    N44[crm_settings.js]
    N45[crm_settings.py]
    N46[test_crm_settings.py]
    N47[__init__.py]
    N48[email_campaign.js]
    N49[email_campaign.py]
    N50[email_campaign_list.js]
    N51[test_email_campaign.py]
    N52[__init__.py]
    N53[lead.js]
    N54[lead.py]
    N55[lead_dashboard.py]
    N56[lead_list.js]
    N57[test_lead.py]
    N58[__init__.py]
    N59[lost_reason_detail.js]
    N60[lost_reason_detail.py]
    N61[__init__.py]
    N62[market_segment.js]
    N63[market_segment.py]
    N64[test_market_segment.py]
    N65[__init__.py]
    N66[opportunity.js]
    N67[opportunity.py]
    N68[opportunity_dashboard.py]
    N69[opportunity_list.js]
    N70[test_opportunity.py]
    N71[__init__.py]
    N72[opportunity_item.py]
    N73[__init__.py]
    N74[opportunity_lost_reason.js]
    N75[opportunity_lost_reason.py]
    N76[__init__.py]
    N77[opportunity_lost_reason_detail.py]
    N78[__init__.py]
    N79[opportunity_type.js]
    N80[opportunity_type.py]
    N81[test_opportunity_type.py]
    N82[__init__.py]
    N83[prospect.js]
    N84[prospect.py]
    N85[test_prospect.py]
    N86[__init__.py]
    N87[prospect_lead.py]
    N88[__init__.py]
    N89[prospect_opportunity.py]
    N90[__init__.py]
    N91[sales_stage.js]
    N92[sales_stage.py]
    N93[test_sales_stage.py]
    N94[utils.py]
    N95[frappe_crm_api.py]
    N96[__init__.py]
    N97[__init__.py]
    N98[campaign_efficiency.js]
    N99[campaign_efficiency.py]
    N100[__init__.py]
    N101[first_response_time_for_opportunity.js]
    N102[first_response_time_for_opportunity.py]
    N103[__init__.py]
    N104[lead_conversion_time.js]
    N105[lead_conversion_time.py]
    N106[__init__.py]
    N107[lead_details.js]
    N108[lead_details.py]
    N109[__init__.py]
    N110[lead_owner_efficiency.js]
    N111[lead_owner_efficiency.py]
    N112[__init__.py]
    N113[lost_opportunity.js]
    N114[lost_opportunity.py]
    N115[__init__.py]
    N116[opportunity_summary_by_sales_stage.js]
    N117[opportunity_summary_by_sales_stage.py]
    N118[test_opportunity_summary_by_sales_stage.py]
    N119[__init__.py]
    N120[prospects_engaged_but_not_converted.js]
    N121[prospects_engaged_but_not_converted.py]
    N122[__init__.py]
    N123[sales_pipeline_analytics.js]
    N124[sales_pipeline_analytics.py]
    N125[test_sales_pipeline_analytics.py]
    N126[utils.py]