graph TD
    N0[__init__.py]
    N1[calendar.py]
    N2[desk_page.py]
    N3[desktop.py]
    N4[__init__.py]
    N5[__init__.py]
    N6[bulk_update.js]
    N7[bulk_update.py]
    N8[test_bulk_update.py]
    N9[__init__.py]
    N10[calendar_view.js]
    N11[calendar_view.py]
    N12[calendar_view_list.js]
    N13[__init__.py]
    N14[changelog_feed.js]
    N15[changelog_feed.py]
    N16[test_changelog_feed.py]
    N17[__init__.py]
    N18[console_log.js]
    N19[console_log.py]
    N20[test_console_log.py]
    N21[__init__.py]
    N22[custom_html_block.js]
    N23[custom_html_block.py]
    N24[test_custom_html_block.py]
    N25[__init__.py]
    N26[dashboard.js]
    N27[dashboard.py]
    N28[dashboard_list.js]
    N29[test_dashboard.py]
    N30[__init__.py]
    N31[dashboard_chart.js]
    N32[dashboard_chart.py]
    N33[test_dashboard_chart.py]
    N34[__init__.py]
    N35[dashboard_chart_field.py]
    N36[__init__.py]
    N37[dashboard_chart_link.py]
    N38[__init__.py]
    N39[dashboard_chart_source.js]
    N40[dashboard_chart_source.py]
    N41[test_dashboard_chart_source.py]
    N42[__init__.py]
    N43[dashboard_settings.js]
    N44[dashboard_settings.py]
    N45[__init__.py]
    N46[desktop_icon.js]
    N47[desktop_icon.py]
    N48[test_desktop_icon.py]
    N49[__init__.py]
    N50[desktop_layout.js]
    N51[desktop_layout.py]
    N52[test_desktop_layout.py]
    N53[__init__.py]
    N54[desktop_settings.js]
    N55[desktop_settings.py]
    N56[test_desktop_settings.py]
    N57[__init__.py]
    N58[event.js]
    N59[event.py]
    N60[event_calendar.js]
    N61[event_list.js]
    N62[test_event.py]
    N63[__init__.py]
    N64[event_notifications.py]
    N65[__init__.py]
    N66[event_participants.py]
    N67[__init__.py]
    N68[form_tour.js]
    N69[form_tour.py]
    N70[__init__.py]
    N71[introduce_ui_tours.py]
    N72[test_form_tour.py]
    N73[__init__.py]
    N74[form_tour_step.py]
    N75[__init__.py]
    N76[global_search_doctype.py]
    N77[__init__.py]
    N78[global_search_settings.js]
    N79[global_search_settings.py]
    N80[__init__.py]
    N81[kanban_board.js]
    N82[kanban_board.py]
    N83[test_kanban_board.py]
    N84[__init__.py]
    N85[kanban_board_column.py]
    N86[__init__.py]
    N87[list_filter.py]
    N88[__init__.py]
    N89[list_view_settings.js]
    N90[list_view_settings.py]
    N91[test_list_view_settings.py]
    N92[__init__.py]
    N93[module_onboarding.js]
    N94[module_onboarding.py]
    N95[test_module_onboarding.py]
    N96[__init__.py]
    N97[note.js]
    N98[note.py]
    N99[note_list.js]
    N100[test_note.py]
    N101[__init__.py]
    N102[note_seen_by.py]
    N103[__init__.py]
    N104[notification_log.js]
    N105[notification_log.py]
    N106[notification_log_list.js]
    N107[test_notification_log.py]
    N108[__init__.py]
    N109[notification_settings.js]
    N110[notification_settings.py]
    N111[test_notification_settings.py]
    N112[__init__.py]
    N113[notification_subscribed_document.py]
    N114[__init__.py]
    N115[number_card.js]
    N116[number_card.py]
    N117[test_number_card.py]
    N118[__init__.py]
    N119[number_card_link.py]
    N120[__init__.py]
    N121[onboarding_permission.js]
    N122[onboarding_permission.py]
    N123[test_onboarding_permission.py]
    N124[__init__.py]
    N125[onboarding_step.js]
    N126[onboarding_step.py]
    N127[test_onboarding_step.py]
    N128[__init__.py]
    N129[onboarding_step_map.py]
    N130[__init__.py]
    N131[route_history.js]
    N132[route_history.py]
    N133[route_history_list.js]
    N134[__init__.py]
    N135[sidebar_item_group.js]
    N136[sidebar_item_group.py]
    N137[test_sidebar_item_group.py]
    N138[__init__.py]
    N139[sidebar_item_group_link.py]
    N140[__init__.py]
    N141[system_console.js]
    N142[system_console.py]
    N143[test_system_console.py]
    N144[__init__.py]
    N145[system_health_report.js]
    N146[system_health_report.py]
    N147[test_system_health_report.py]
    N148[__init__.py]
    N149[system_health_report_errors.py]
    N150[__init__.py]
    N151[system_health_report_failing_jobs.py]
    N152[__init__.py]
    N153[system_health_report_queue.py]
    N154[__init__.py]
    N155[system_health_report_tables.py]
    N156[__init__.py]
    N157[system_health_report_workers.py]
    N158[__init__.py]
    N159[tag.js]
    N160[tag.py]
    N161[test_tag.py]
    N162[__init__.py]
    N163[tag_link.js]
    N164[tag_link.py]
    N165[test_tag_link.py]
    N166[__init__.py]
    N167[test_todo.py]
    N168[todo.js]
    N169[todo.py]
    N170[todo_calendar.js]
    N171[todo_list.js]
    N172[__init__.py]
    N173[update_app.py]
    N174[test_workspace.py]
    N175[workspace.js]
    N176[workspace.py]
    N177[__init__.py]
    N178[workspace_chart.py]
    N179[__init__.py]
    N180[workspace_custom_block.py]
    N181[__init__.py]
    N182[workspace_link.py]
    N183[__init__.py]
    N184[workspace_number_card.py]
    N185[__init__.py]
    N186[workspace_quick_list.py]
    N187[__init__.py]
    N188[workspace_shortcut.py]
    N189[__init__.py]
    N190[test_workspace_sidebar.py]
    N191[workspace_sidebar.js]
    N192[workspace_sidebar.py]
    N193[__init__.py]
    N194[workspace_sidebar_item.py]
    N195[__init__.py]
    N196[assign_to.py]
    N197[document_follow.py]
    N198[linked_with.py]
    N199[load.py]
    N200[meta.py]
    N201[save.py]
    N202[test_form.py]
    N203[utils.py]
    N204[gantt.py]
    N205[like.py]
    N206[link_preview.py]
    N207[listview.py]
    N208[notifications.py]
    N209[__init__.py]
    N210[__init__.py]
    N211[backups.js]
    N212[backups.py]
    N213[__init__.py]
    N214[desktop.js]
    N215[desktop.py]
    N216[__init__.py]
    N217[install_fixtures.py]
    N218[setup_wizard.js]
    N219[setup_wizard.py]
    N220[query_report.py]
    N221[__init__.py]
    N222[__init__.py]
    N223[todo.js]
    N224[todo.py]
    N225[reportview.py]
    N226[search.py]
    N227[treeview.py]
    N228[utils.py]