graph TD
    N0[__init__.py]
    N1[__init__.py]
    N2[item_dashboard.js]
    N3[item_dashboard.py]
    N4[warehouse_capacity_dashboard.py]
    N5[__init__.py]
    N6[__init__.py]
    N7[stock_value_by_item_group.js]
    N8[stock_value_by_item_group.py]
    N9[__init__.py]
    N10[warehouse_wise_stock_value.js]
    N11[warehouse_wise_stock_value.py]
    N12[deprecated_serial_batch.py]
    N13[__init__.py]
    N14[__init__.py]
    N15[batch.js]
    N16[batch.py]
    N17[batch_dashboard.py]
    N18[batch_list.js]
    N19[test_batch.py]
    N20[__init__.py]
    N21[bin.js]
    N22[bin.py]
    N23[test_bin.py]
    N24[__init__.py]
    N25[customs_tariff_number.js]
    N26[customs_tariff_number.py]
    N27[test_customs_tariff_number.py]
    N28[__init__.py]
    N29[delivery_note.js]
    N30[delivery_note.py]
    N31[delivery_note_dashboard.py]
    N32[delivery_note_list.js]
    N33[__init__.py]
    N34[drop_unused_return_against_index.py]
    N35[test_delivery_note.py]
    N36[__init__.py]
    N37[delivery_note_item.py]
    N38[__init__.py]
    N39[delivery_settings.js]
    N40[delivery_settings.py]
    N41[test_delivery_settings.py]
    N42[__init__.py]
    N43[delivery_stop.py]
    N44[__init__.py]
    N45[delivery_trip.js]
    N46[delivery_trip.py]
    N47[delivery_trip_list.js]
    N48[test_delivery_trip.py]
    N49[__init__.py]
    N50[inventory_dimension.js]
    N51[inventory_dimension.py]
    N52[test_inventory_dimension.py]
    N53[__init__.py]
    N54[item.js]
    N55[item.py]
    N56[item_dashboard.py]
    N57[item_list.js]
    N58[test_item.py]
    N59[__init__.py]
    N60[item_alternative.js]
    N61[item_alternative.py]
    N62[test_item_alternative.py]
    N63[__init__.py]
    N64[item_attribute.js]
    N65[item_attribute.py]
    N66[test_item_attribute.py]
    N67[__init__.py]
    N68[item_attribute_value.py]
    N69[__init__.py]
    N70[item_barcode.py]
    N71[__init__.py]
    N72[item_customer_detail.py]
    N73[__init__.py]
    N74[item_default.py]
    N75[__init__.py]
    N76[item_lead_time.js]
    N77[item_lead_time.py]
    N78[test_item_lead_time.py]
    N79[__init__.py]
    N80[item_manufacturer.js]
    N81[item_manufacturer.py]
    N82[test_item_manufacturer.py]
    N83[__init__.py]
    N84[item_price.js]
    N85[item_price.py]
    N86[item_price_list.js]
    N87[test_item_price.py]
    N88[__init__.py]
    N89[item_quality_inspection_parameter.py]
    N90[__init__.py]
    N91[item_reorder.py]
    N92[__init__.py]
    N93[item_supplier.py]
    N94[__init__.py]
    N95[item_tax.py]
    N96[__init__.py]
    N97[item_variant.py]
    N98[__init__.py]
    N99[item_variant_attribute.py]
    N100[__init__.py]
    N101[item_variant_settings.js]
    N102[item_variant_settings.py]
    N103[test_item_variant_settings.py]
    N104[__init__.py]
    N105[item_website_specification.py]
    N106[__init__.py]
    N107[landed_cost_item.py]
    N108[__init__.py]
    N109[landed_cost_purchase_receipt.py]
    N110[__init__.py]
    N111[landed_cost_taxes_and_charges.py]
    N112[__init__.py]
    N113[landed_cost_vendor_invoice.py]
    N114[__init__.py]
    N115[landed_cost_voucher.js]
    N116[landed_cost_voucher.py]
    N117[test_landed_cost_voucher.py]
    N118[__init__.py]
    N119[manufacturer.js]
    N120[manufacturer.py]
    N121[test_manufacturer.py]
    N122[__init__.py]
    N123[material_request.js]
    N124[material_request.py]
    N125[material_request_dashboard.py]
    N126[material_request_list.js]
    N127[test_material_request.py]
    N128[__init__.py]
    N129[material_request_item.py]
    N130[__init__.py]
    N131[packed_item.py]
    N132[test_packed_item.py]
    N133[__init__.py]
    N134[packing_slip.js]
    N135[packing_slip.py]
    N136[test_packing_slip.py]
    N137[__init__.py]
    N138[packing_slip_item.py]
    N139[__init__.py]
    N140[pick_list.js]
    N141[pick_list.py]
    N142[pick_list_dashboard.py]
    N143[pick_list_list.js]
    N144[test_pick_list.py]
    N145[__init__.py]
    N146[pick_list_item.py]
    N147[__init__.py]
    N148[price_list.js]
    N149[price_list.py]
    N150[test_price_list.py]
    N151[__init__.py]
    N152[price_list_country.py]
    N153[__init__.py]
    N154[purchase_receipt.js]
    N155[purchase_receipt.py]
    N156[purchase_receipt_dashboard.py]
    N157[purchase_receipt_list.js]
    N158[test_purchase_receipt.py]
    N159[__init__.py]
    N160[purchase_receipt_item.py]
    N161[__init__.py]
    N162[putaway_rule.js]
    N163[putaway_rule.py]
    N164[putaway_rule_list.js]
    N165[test_putaway_rule.py]
    N166[__init__.py]
    N167[quality_inspection.js]
    N168[quality_inspection.py]
    N169[test_quality_inspection.py]
    N170[__init__.py]
    N171[quality_inspection_parameter.js]
    N172[quality_inspection_parameter.py]
    N173[test_quality_inspection_parameter.py]
    N174[__init__.py]
    N175[quality_inspection_parameter_group.js]
    N176[quality_inspection_parameter_group.py]
    N177[test_quality_inspection_parameter_group.py]
    N178[__init__.py]
    N179[quality_inspection_reading.py]
    N180[__init__.py]
    N181[quality_inspection_template.js]
    N182[quality_inspection_template.py]
    N183[test_quality_inspection_template.py]
    N184[__init__.py]
    N185[quick_stock_balance.js]
    N186[quick_stock_balance.py]
    N187[__init__.py]
    N188[repost_item_valuation.js]
    N189[repost_item_valuation.py]
    N190[repost_item_valuation_list.js]
    N191[test_repost_item_valuation.py]
    N192[__init__.py]
    N193[serial_and_batch_bundle.js]
    N194[serial_and_batch_bundle.py]
    N195[serial_and_batch_bundle_list.js]
    N196[test_serial_and_batch_bundle.py]
    N197[__init__.py]
    N198[serial_and_batch_entry.py]
    N199[__init__.py]
    N200[serial_no.js]
    N201[serial_no.py]
    N202[test_serial_no.py]
    N203[__init__.py]
    N204[shipment.js]
    N205[shipment.py]
    N206[shipment_list.js]
    N207[test_shipment.py]
    N208[__init__.py]
    N209[shipment_delivery_note.py]
    N210[__init__.py]
    N211[shipment_parcel.py]
    N212[__init__.py]
    N213[shipment_parcel_template.js]
    N214[shipment_parcel_template.py]
    N215[test_shipment_parcel_template.py]
    N216[__init__.py]
    N217[stock_closing_balance.js]
    N218[stock_closing_balance.py]
    N219[test_stock_closing_balance.py]
    N220[__init__.py]
    N221[stock_closing_entry.js]
    N222[stock_closing_entry.py]
    N223[stock_closing_entry_dashboard.py]
    N224[stock_closing_entry_list.js]
    N225[test_stock_closing_entry.py]
    N226[__init__.py]
    N227[stock_entry.js]
    N228[stock_entry.py]
    N229[stock_entry_dashboard.py]
    N230[stock_entry_list.js]
    N231[stock_entry_utils.py]
    N232[test_stock_entry.py]
    N233[__init__.py]
    N234[stock_entry_detail.py]
    N235[__init__.py]
    N236[stock_entry_type.js]
    N237[stock_entry_type.py]
    N238[test_stock_entry_type.py]
    N239[__init__.py]
    N240[__init__.py]
    N241[ensure_sle_indexes.py]
    N242[stock_ledger_entry.js]
    N243[stock_ledger_entry.py]
    N244[test_stock_ledger_entry.py]
    N245[__init__.py]
    N246[stock_reconciliation.js]
    N247[stock_reconciliation.py]
    N248[test_stock_reconciliation.py]
    N249[__init__.py]
    N250[stock_reconciliation_item.py]
    N251[__init__.py]
    N252[stock_reposting_settings.js]
    N253[stock_reposting_settings.py]
    N254[test_stock_reposting_settings.py]
    N255[__init__.py]
    N256[stock_reservation_entry.js]
    N257[stock_reservation_entry.py]
    N258[stock_reservation_entry_list.js]
    N259[test_stock_reservation_entry.py]
    N260[__init__.py]
    N261[stock_settings.js]
    N262[stock_settings.py]
    N263[test_stock_settings.py]
    N264[__init__.py]
    N265[test_uom_category.py]
    N266[uom_category.js]
    N267[uom_category.py]
    N268[__init__.py]
    N269[uom_conversion_detail.py]
    N270[__init__.py]
    N271[test_variant_field.py]
    N272[variant_field.js]
    N273[variant_field.py]
    N274[__init__.py]
    N275[test_warehouse.py]
    N276[warehouse.js]
    N277[warehouse.py]
    N278[warehouse_tree.js]
    N279[__init__.py]
    N280[test_warehouse_type.py]
    N281[warehouse_type.js]
    N282[warehouse_type.py]
    N283[get_item_details.py]
    N284[__init__.py]
    N285[__init__.py]
    N286[stock_balance.js]
    N287[__init__.py]
    N288[warehouse_capacity_summary.js]
    N289[__init__.py]
    N290[__init__.py]
    N291[__init__.py]
    N292[__init__.py]
    N293[__init__.py]
    N294[reorder_item.py]
    N295[__init__.py]
    N296[__init__.py]
    N297[available_batch_report.js]
    N298[available_batch_report.py]
    N299[__init__.py]
    N300[available_serial_no.js]
    N301[available_serial_no.py]
    N302[test_available_serial_no.py]
    N303[__init__.py]
    N304[batch_item_expiry_status.js]
    N305[batch_item_expiry_status.py]
    N306[__init__.py]
    N307[batch_wise_balance_history.js]
    N308[batch_wise_balance_history.py]
    N309[__init__.py]
    N310[bom_search.js]
    N311[bom_search.py]
    N312[__init__.py]
    N313[cogs_by_item_group.js]
    N314[cogs_by_item_group.py]
    N315[__init__.py]
    N316[delayed_item_report.js]
    N317[delayed_item_report.py]
    N318[__init__.py]
    N319[delayed_order_report.js]
    N320[delayed_order_report.py]
    N321[__init__.py]
    N322[delivery_note_trends.js]
    N323[delivery_note_trends.py]
    N324[__init__.py]
    N325[fifo_queue_vs_qty_after_transaction_comparison.js]
    N326[fifo_queue_vs_qty_after_transaction_comparison.py]
    N327[__init__.py]
    N328[incorrect_balance_qty_after_transaction.js]
    N329[incorrect_balance_qty_after_transaction.py]
    N330[__init__.py]
    N331[incorrect_serial_and_batch_bundle.js]
    N332[incorrect_serial_and_batch_bundle.py]
    N333[__init__.py]
    N334[incorrect_serial_no_valuation.js]
    N335[incorrect_serial_no_valuation.py]
    N336[__init__.py]
    N337[incorrect_stock_value_report.js]
    N338[incorrect_stock_value_report.py]
    N339[__init__.py]
    N340[__init__.py]
    N341[item_price_stock.js]
    N342[item_price_stock.py]
    N343[__init__.py]
    N344[item_prices.js]
    N345[item_prices.py]
    N346[__init__.py]
    N347[item_shortage_report.js]
    N348[item_shortage_report.py]
    N349[test_item_shortage_report.py]
    N350[__init__.py]
    N351[item_variant_details.js]
    N352[item_variant_details.py]
    N353[__init__.py]
    N354[__init__.py]
    N355[__init__.py]
    N356[itemwise_recommended_reorder_level.js]
    N357[itemwise_recommended_reorder_level.py]
    N358[__init__.py]
    N359[landed_cost_report.js]
    N360[landed_cost_report.py]
    N361[__init__.py]
    N362[__init__.py]
    N363[product_bundle_balance.js]
    N364[product_bundle_balance.py]
    N365[__init__.py]
    N366[purchase_receipt_trends.js]
    N367[purchase_receipt_trends.py]
    N368[__init__.py]
    N369[__init__.py]
    N370[reserved_stock.js]
    N371[reserved_stock.py]
    N372[test_reserved_stock.py]
    N373[__init__.py]
    N374[__init__.py]
    N375[serial_and_batch_summary.js]
    N376[serial_and_batch_summary.py]
    N377[__init__.py]
    N378[serial_no_and_batch_traceability.js]
    N379[serial_no_and_batch_traceability.py]
    N380[__init__.py]
    N381[serial_no_ledger.js]
    N382[serial_no_ledger.py]
    N383[__init__.py]
    N384[__init__.py]
    N385[__init__.py]
    N386[__init__.py]
    N387[stock_ageing.js]
    N388[stock_ageing.py]
    N389[test_stock_ageing.py]
    N390[__init__.py]
    N391[stock_analytics.js]
    N392[stock_analytics.py]
    N393[test_stock_analytics.py]
    N394[__init__.py]
    N395[stock_and_account_value_comparison.js]
    N396[stock_and_account_value_comparison.py]
    N397[__init__.py]
    N398[stock_balance.js]
    N399[stock_balance.py]
    N400[test_stock_balance.py]
    N401[__init__.py]
    N402[stock_ledger.js]
    N403[stock_ledger.py]
    N404[test_stock_ledger_report.py]
    N405[__init__.py]
    N406[stock_ledger_invariant_check.js]
    N407[stock_ledger_invariant_check.py]
    N408[__init__.py]
    N409[stock_ledger_variance.js]
    N410[stock_ledger_variance.py]
    N411[__init__.py]
    N412[stock_projected_qty.js]
    N413[stock_projected_qty.py]
    N414[__init__.py]
    N415[stock_qty_vs_batch_qty.js]
    N416[stock_qty_vs_batch_qty.py]
    N417[__init__.py]
    N418[stock_qty_vs_serial_no_count.js]
    N419[stock_qty_vs_serial_no_count.py]
    N420[__init__.py]
    N421[supplier_wise_sales_analytics.js]
    N422[supplier_wise_sales_analytics.py]
    N423[test_reports.py]
    N424[__init__.py]
    N425[total_stock_summary.js]
    N426[total_stock_summary.py]
    N427[__init__.py]
    N428[warehouse_wise_item_balance_age_and_value.js]
    N429[warehouse_wise_item_balance_age_and_value.py]
    N430[__init__.py]
    N431[warehouse_wise_stock_balance.js]
    N432[warehouse_wise_stock_balance.py]
    N433[serial_batch_bundle.py]
    N434[stock_balance.py]
    N435[stock_ledger.py]
    N436[test_get_item_details.py]
    N437[test_utils.py]
    N438[test_valuation.py]
    N439[utils.py]
    N440[valuation.py]