import frappe
from frappe.model.document import Document


class AutoGeneratedDocRegistry(Document):
    def validate(self):
        # Enforce one-target-one-row at app level (Frappe doesn't yet support
        # multi-column unique without DB migration noise).
        if not self.is_new():
            return
        existing = frappe.db.get_value(
            "Auto Generated Doc Registry",
            {"target_doctype": self.target_doctype, "target_name": self.target_name},
            "name",
        )
        if existing:
            frappe.throw(
                frappe._("Đã đăng ký rồi: {0} {1} (registry id: {2})").format(
                    self.target_doctype, self.target_name, existing
                )
            )
